### ISSUE TITLE
Feature request: Enqueue every x seconds

### ISSUE THREAD

**Issue by lichtamberg** [ondrejbartas/sidekiq-cron#103]
Hi,

At first: Thanks for your great work!

And here is my feature request:

It would be nice if you could add somehow the option, to run tasks not only for example once per minute, but for example every ten seconds. I don't know how it will fit to the cron syntax, but maybe there is a way?

What do you think?

Thanks!

**Comment by tfluehmann** [comment]
Hi lichtamberg

The cron syntax only supports granularity until a minute.
Why do you need smaller intervalls?
You could run a standalone process that does it for you with a sleep.

Cheers

**Comment by lichtamberg** [comment]
Yeah, i noticed that... :(

I'm fetching financial data from public sources, about 4 times a minute (no long polling possible).
Your suggestion is even my current setup, but as you can think, it takes up 4x the resources, which I would like to reduce..

**Comment by eterry1388** [comment]
This is already supported.  See https://github.com/ondrejbartas/sidekiq-cron/issues/67 and https://github.com/ondrejbartas/sidekiq-cron/issues/26

**Comment by eterry1388** [comment]
Also, be sure to set the `average_scheduled_poll_interval` to something small (like every 10 seconds).

For example:

```ruby
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://localhost:6379/12' }
  config.average_scheduled_poll_interval = 10
end
```
