### ISSUE TITLE
attr_reader: for the queue

### ISSUE THREAD

**Issue by tfluehmann** [ondrejbartas/sidekiq-cron#104]
Dear all,

We have an issue that we have to re-enqueue the sidekiq-cron jobs on every deploy because there could be some new. While runtime we create dynamically new cronable jobs, they are deleted because we reload all of them (as written above). We have implemented a kind of hack that stores these dynamically created jobs on deploy and puts them back afterwards. 
The problem is, that we cannot access the queue we have defined for these jobs (except, job.instance_variable_get....) would you agree to create an attribute reader for the queue?
Or doesn't it make any sense to you?

Here is an example
https://gist.github.com/tfluehmann/8807ce5d4ada60c57a39ddbbb9c131d5

Thx

**Comment by ondrejbartas** [comment]
@tfluehmann you should not use

```
Sidekiq::Cron::Job#load_from_hash! hash
Sidekiq::Cron::Job#load_from_array! array
```

when you use not bang method, it will not remove anything, it will just update jobs you are setting up so it will work afterwards with your dynamically added cronable jobs.
