### ISSUE TITLE
Validate `schedule.yml` class names

### ISSUE THREAD

**Issue by faucct** [ondrejbartas/sidekiq-cron#105]
Hello, it seems that `Sidekiq::Cron::Job.load_from_hash!` does not return any errors if the class specified in `schedule.yml` does not exist. Is there any way to validate it?

**Comment by ondrejbartas** [comment]
Its tricky, because job can be added directly in redis. Other thing is separation where one part of application know what to schedule and workers are running code from different code base. So maybe there can be method `validate?` which will raise exception for you.
