### ISSUE TITLE
Feature request: Previous and current creation times

### ISSUE THREAD

**Issue by mahemoff** [ondrejbartas/sidekiq-cron#106]
Similar to [Sidetiq's default time arguments](https://github.com/tobiassvn/sidetiq/wiki/Basic-Usage), I'd like a way for workers to get the current and previous job creation times. For example:

```
{
 'name'  => 'name_of_job', #must be uniq!
 'cron'  => '1 * * * *',
 'class' => 'MyClass',
 'args'  => ['foo', 'bar', Sidekiq::Cron::PREVIOUS_CREATION_TIME, Sidekiq::Cron::CURRENT_CREATION_TIME]
}
```

When the job is created,the time arguments would be replaced with the minute-rounded time that triggered job creation.

This would be useful for repeating jobs - each instance can do work on a particular time slice.

**Comment by syedali90** [comment]
any update on this ?
