### ISSUE TITLE
how to pass args to CronJobs ?

### ISSUE THREAD

**Issue by syedali90** [ondrejbartas/sidekiq-cron#108]
Sidekiq::Cron::Job.create(name: 'Hard worker - every 5min', cron: '*/5 * * * *', class: 'HardWorker')

how would i pass name and count ?
if i'm running cron job from with in HardWorker class 

class HardWorker
  include Sidekiq::Worker
  def perform(name, count)
    # do something
  end
end

**Comment by ondrejbartas** [comment]
Hi. `args` is option you are looking for.

```
args = [name, count]
```

**Comment by syedali90** [comment]
umm.. I was asking that If I had to call cronjob from with in worker class, is there any way to do that ..

**Comment by ondrejbartas** [comment]
Sorry @syedali90 but I am not getting what you are talking about.

Cron jobs are adding jobs to schedule queue. You are not calling Sidekiq::Cron::Job from your workers at all. You just need to call this only one time on initialization or from console 💃

**Comment by syedali90** [comment]
ah .. in my logical, i had initialize a cron job from other worker ..

**Comment by salismt** [comment]
@ondrejbartas I am able to pass the arguments

`    Sidekiq::Cron::Job.create(name: "Hard worker - every 5min", cron: "*/1 * * * *", class: 'HardWorker', args: ["bob", "3"])
`
And this is my worker
```
class HardWorker
  include Sidekiq::Worker

  def perform(name, count)
    p "Hello #{name} count #{count}"
    p "Welcome to sidekiq"
  end
end
```

it prints out this
```
2019-03-05T09:16:21.831Z 86713 TID-ovva3uwx1 HardWorker JID-e9f7519aa8af67859e9b1961 INFO: start
"Hello bob count 3"
"Welcome to sidekiq"
2019-03-05T09:16:21.846Z 86713 TID-ovva3uwx1 HardWorker JID-e9f7519aa8af67859e9b1961 INFO: done: 0.015 sec
2019-03-05T09:17:00.214Z 86713 TID-ovv9xku2p HardWorker JID-205fcdff31292e7d047a6e19 INFO: start
2019-03-05T09:17:00.215Z 86713 TID-ovv9xku2p HardWorker JID-205fcdff31292e7d047a6e19 INFO: fail: 0.001 sec
```

but it says that I don't have enough arguments
```
{"context":"Job raised exception","job":{"queue":"default","args":[],"class":"HardWorker","retry":true,"jid":"205fcdff31292e7d047a6e19","created_at":1551777381.8244522,"enqueued_at":1551777420.213175,"error_message":"wrong number of arguments (given 0, expected 2)","error_class":"ArgumentError","failed_at":1551777381.825769,"retry_count":0},"jobstr":"{\"queue\":\"default\",\"args\":[],\"class\":\"HardWorker\",\"retry\":true,\"jid\":\"205fcdff31292e7d047a6e19\",\"created_at\":1551777381.8244522,\"enqueued_at\":1551777420.213175,\"error_message\":\"wrong number of arguments (given 0, expected 2)\",\"error_class\":\"ArgumentError\",\"failed_at\":1551777381.825769,\"retry_count\":0}"}
```

I already clear the redis with `redis-cli FLUSHALL`
but I still get this error, even tho I only trigger it once

**Comment by salismt** [comment]
nevermind, turns out when I check on the sidekiq monitoring, I have another crons running from `schedule.yml`
