### ISSUE TITLE
cron jobs not excuted if scheduled when sidekiq is restarted during deploy

### ISSUE THREAD

**Issue by cswilliams** [ondrejbartas/sidekiq-cron#111]
Hi,

I was curious if anyone had dealt with the issue of cron jobs not running while sidekiq is restarting (e.g. after a deploy).  We've run into this issue a couple times now where a job was scheduled at the exact time our sidekiq process was restarting due to a deploy, so the job never ran.

Is there a proper way to handle this case so we don't lose scheduling when restarting sidekiq?  It seems like sidekiq-cron would need some mechanism to keep track of any jobs that should of been executed while it was stopped or perhaps some fancy restart mechanism?  Anyhow, was curious if you guys had already thought through this problem at all.

Thanks,
-Chris

**Comment by cswilliams** [comment]
Just an update, I'm going to try the following and see if it keeps the issue from happening:

1) Send a USR1 to the old sidekiq process 
2) start up the new sidekiq process
3) after new sidekiq process starts, send a TERM to the old sidekiq process

This should hopefully minimize any time where the cron scheduler isn't running...

**Comment by ondrejbartas** [comment]
@cswilliams Hi, @MMartyn fixed this problem. It will not happen with new released version

**Comment by phyzalis** [comment]
I am facing nearly the same issue

While deploying with Capistrano, Sidekiq process is set to quiet then stoped then a new Sidekiq process starts

But all tasked scheduled during this quiet + stoped phase seems to be lost. Could you tell me in which version it has been fixed ? Thank you very much
