### ISSUE TITLE
Sidekiq 4.1.4

### ISSUE THREAD

**Issue by aahmad** [ondrejbartas/sidekiq-cron#112]
We currently have a few services which were on Sidekiq 3, but we upgraded to Sidekiq 4.1.4. We also upgraded sidekiq-cron to 0.4.2. 

Every thing seems to be running perfectly fine on the other services, however, one has had persistent issues just start up a few days after we rolled out the upgrades. We have 5 Sidekiq servers running 4 threads each. Namely, minutely jobs are now running every 4-5 minutes. Jobs which are meant to run every 15 minutes haven't run in 32 minutes. 

We have cleared all items in the cron namespace on Redis to no avail. Sidekiq logs do not show anything unusual. Hitting the Enqueue Now button on sidekiq-web enqueues the job correctly...

This service is quite busy as far as the workers running on a minutely basis, but the RoR service is running fine without any bottlenecks. The queues are not busy and the servers are not overloaded. 

Thank you for any insight and troubleshooting guidance. 

Afra

**Comment by EvanMcEwen** [comment]
Possibly related to #89 ? See my last post; I seem to be having a similar issue to you but my jobs/sidekiq server is no where near as busy as yours sound.

**Comment by EvanMcEwen** [comment]
@aahmad Did you ever figure out a solution? I ended up rolling back to Sidekiq 3.5.1 and Sidekiq-cron 0.3.1 and everything is normal again for me.

**Comment by ondrejbartas** [comment]
it should work with sidekiq 5 #138
