### ISSUE TITLE
Feature Request: Mark Job as disabled in yaml file

### ISSUE THREAD

**Issue by sanjaygoel** [ondrejbartas/sidekiq-cron#118]
Hi, 
It would be great if in sidekiq_schedule.yaml file, we can also specify a parameter enabled: true. 
Many times a certain job needs to be disabled temporarily and commenting it out is not a great idea. I tried using the UI but it takes time, and the job already gets started by that time. 

Thanks
Sanjay

**Comment by Linell** [comment]
You can actually do this already. This is how it works:

```ruby
foo_task:
  cron:   "*/30 * * * *"
  class:  "TaskFooFoo"
  status: "disabled"

```
