### ISSUE TITLE
Test fails when run after 23 hours: ArgumentError: argument out of range

### ISSUE THREAD

**Issue by pravi** [ondrejbartas/sidekiq-cron#119]
When the test was run at 2016-11-18T23:41:43Z with the debian package it failed with `ArgumentError: argument out of range` because `enqueued_time = Time.new(now.year, now.month, now.day, now.hour + 1, 8, 1)` will try to create time for hour 24 which is out of range. Full log is http://aws-logs.debian.net/2016/11/18/ruby-sidekiq-cron_0.4.2-5_unstable.log

Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844925

**Comment by ondrejbartas** [comment]
fixed
