### ISSUE TITLE
Cron jobs failing after upgrade to Rufus Scheduler 3.3

### ISSUE THREAD

**Issue by liveh2o** [ondrejbartas/sidekiq-cron#122]
Upgrading to Rufus Scheduler v3.3.0 causes cron jobs not to be scheduled. Instead, an error is logged:

```
[ERROR] [2016-11-30 09:24:57 -0700] CRON JOB: can't convert Rufus::Scheduler::ZoTime into an exact number
[ERROR] [2016-11-30 09:24:57 -0700] CRON JOB: /Users/ah/.rvm/gems/ruby-2.3.3@persona/gems/activesupport-4.2.7.1/lib/active_support/core_ext/time/calculations.rb:233:in `-'
```

Downgrading to Rufus Schedler v3.2.2 resolves the issue.

Based on the changelog for the v3.3.0 release:

```
- Bring in Piavka's Job#trigger_off_schedule, gh-214
- Reject "day 0" in cronlines, thanks to Ramon Tayag, https://github.com/ramontayag
- Move away from ENV['TZ'], thanks to Akinori Musha, https://github.com/knu
- Fix .parse_to_time vs Date issue, as reported by @nsatragno
```

My guess would be that it was the move away from `ENV['TZ']` to resolve jmettraux/rufus-scheduler#220 that is causing problems as there are [several commits](https://github.com/jmettraux/rufus-scheduler/compare/781c009d97...184bd6ab347) that reference `ZoTime`.

**Comment by turley** [comment]
Appears to be a duplicate of https://github.com/ondrejbartas/sidekiq-cron/issues/120 (fixed by https://github.com/ondrejbartas/sidekiq-cron/pull/121).

**Comment by liveh2o** [comment]
Definitely a duplicate. Guess I missed it because it was closed. Any idea when #121 will be released?
