### ISSUE TITLE
Hook into Exception Handling

### ISSUE THREAD

**Issue by tisba** [ondrejbartas/sidekiq-cron#123]
We ran into https://github.com/ondrejbartas/sidekiq-cron/pull/121 and I was wondering why Rollbar (via https://github.com/rollbar/rollbar-gem) did not report the exception.

Looking at https://github.com/ondrejbartas/sidekiq-cron/blob/master/lib/sidekiq/cron/poller.rb it looks like errors are only logged. Other sidekiq errors are catched by https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/plugins/sidekiq.rb which seems not to be the case with sidekiq-cron related errors.

I'm not 100% sure what needs to be done, but I think a way to hook into the exception handling would be nice to have with sidekiq-cron. This way we (or maybe the rollbar team) could provide a plugin to hook into the exception handling and report the error.

**Comment by tisba** [comment]
Hey @ondrejbartas. Has this issue been resolved? I could not find any commit/changes in relation to this issue…

**Comment by ondrejbartas** [comment]
I have added exception handler #190
