### ISSUE TITLE
Bug when trying to recover a Job

### ISSUE THREAD

**Issue by arrubo** [ondrejbartas/sidekiq-cron#124]
Sidekiq-cron is updated to last: Installing sidekiq-cron 0.4.5 (was 0.4.4)
When trying to recover a job by name or all the jobs ... 
 - Sidekiq::Cron::Job.all
 - Sidekiq::Cron::Job.find("name of a job")
It seems that 'default' is not initializated in the method 'initialize' ... /job.rb:290
Backtrace error:
NameError: undefined local variable or method `default' for #<Sidekiq::Cron::Job:0x0000000856e098>
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/sidekiq-cron-0.4.5/lib/sidekiq/cron/job.rb:290:in `initialize'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/sidekiq-cron-0.4.5/lib/sidekiq/cron/job.rb:213:in `new'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/sidekiq-cron-0.4.5/lib/sidekiq/cron/job.rb:213:in `block in all'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/sidekiq-cron-0.4.5/lib/sidekiq/cron/job.rb:211:in `collect'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/sidekiq-cron-0.4.5/lib/sidekiq/cron/job.rb:211:in `all'
        from (irb):1
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
        from /home/rubengonzalez/ror/costboard/bin/rails:9:in `<top (required)>'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/spring-2.0.0/lib/spring/commands/rails.rb:6:in `call'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/spring-2.0.0/lib/spring/command_wrapper.rb:38:in `call'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/spring-2.0.0/lib/spring/application.rb:191:in `block in serve'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/spring-2.0.0/lib/spring/application.rb:161:in `fork'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/spring-2.0.0/lib/spring/application.rb:161:in `serve'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/spring-2.0.0/lib/spring/application.rb:131:in `block in run'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/spring-2.0.0/lib/spring/application.rb:125:in `loop'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/spring-2.0.0/lib/spring/application.rb:125:in `run'
        from /home/rubengonzalez/.rvm/gems/ruby-2.3.1@costboard/gems/spring-2.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /home/rubengonzalez/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/rubengonzalez/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'

**Comment by ondrejbartas** [comment]
fixed in version 0.5.1
