### ISSUE TITLE
cron job sidekiq error

### ISSUE THREAD

**Issue by tomwey** [ondrejbartas/sidekiq-cron#125]
ERROR: CRON JOB: can't convert Rufus::Scheduler::ZoTime into an exact number
2016-12-07T08:37:16.663Z 54023 TID-ove97gil0 ERROR: CRON JOB: /Users/tangwei1/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/core_ext/time/calculations.rb:232:in `-'

**Comment by dreyks** [comment]
this is already fixed in master

@ondrejbartas I see that you already bumped version to 0.4.5 Would you please cut a new release? Thanks!

**Comment by dreyks** [comment]
Oh, actually 0.4.5 is already released on rubygems so just update your bundle

**Comment by tomwey** [comment]
ok, i try it

**Comment by Tkwon123** [comment]
There wasn't a tag on the release, but I see that 0.4.5 in fact resolved this issue for me

**Comment by ondrejbartas** [comment]
relesaed 0.5.1
