### ISSUE TITLE
Wrong release Date in gemspec/on rubygems.org

### ISSUE THREAD

**Issue by themilkman** [ondrejbartas/sidekiq-cron#126]
Hi there, 

since it reeeeally confused just wanted to notice that the gemspec of version 0.4.5 has an old fixed release date - which is also shown on rubygems.org.

` s.date = "2016-09-22"`

I think this is not intended, is it? Anyway, thanks for the release.

Cheers!

**Comment by ondrejbartas** [comment]
thanks for pointing this out, I made mistake when creating new release.
