### ISSUE TITLE
Number of threads is increasing consistently after every scheduled job is triggered.

### ISSUE THREAD

**Issue by bitfurry** [ondrejbartas/sidekiq-cron#129]
Hi, 
I am using latest version of sidekiq-cron, for scheduling job after very one minute, the problem we are facing is that the number of threads for sidekiq process keep of increasing over time, it adds up after one  minute. 
I'm using jruby-9.1.6.0, with sidekiq-pro.

Please let me know if you want any further info ? @ondrejbartas

**Comment by ondrejbartas** [comment]
@bitfurry that is very strange. Sidekiq cron should not add any new thread to your application, try to remove sidekiq cron from your app and test thread count...

**Comment by ondrejbartas** [comment]
pls paste your versions of sidekiq and sidekiq-cron

**Comment by bitfurry** [comment]
@ondrejbartas the versions are following: 
 sidekiq (4.2.7)
    sidekiq-cron (0.4.5)

**Comment by bitfurry** [comment]
I am using Sidekiq cron to trigger a job after every 1 minute, and thread count increases by 1 after every job is triggered. So how do you suggest I remove sidekiq-cron from my app, since after that I can't trigger the job . Am I making any sense to you ? Please feel free to correct me, I might be wrong 
@ondrejbartas

**Comment by ondrejbartas** [comment]
@bitfurry just make sure that Sidekiq-Cron is one that is responsible for increasing thread count number.

I sugested that you will remove sidekiq cron (Gemfile `require: false`) and comment out all Sidekiq Corn lines (in your code) and than run your app. You can trigger job adding (same as Sidekiq Cron is doing) by `YourWorker.perform_async()` 

After that check thread count...

I don't think that Sidekiq cron will increasethread count at all. :(

**Comment by bitfurry** [comment]
sorry for troubling you, there was a bug from our end. Thanks a lot @ondrejbartas for the quick responses.
