### ISSUE TITLE
Web doesn't work if gem is not loaded

### ISSUE THREAD

**Issue by HoneyryderChuck** [ondrejbartas/sidekiq-cron#130]
Contrast with sidekiq:

If I have `gem "sidekiq", require: false` in my Gemfile, and require `sidekiq/web` in my config.ru, it just works.

If I have the same setup with this gem, it breaks. It seems to expect `Sidekiq::Cron::Job` to be in memory already.

My workaround:

```
require "sidekiq/web"
 require "sidekiq/cron/job"
 require "sidekiq/cron/web"
 map '/jobs' do
   run Sidekiq::Web
 end
```

requiring the web component **must** require the job component, if it really needs it.

**Comment by ondrejbartas** [comment]
you can remove require: false from gemfile and then it will work 👍

**Comment by ondrejbartas** [comment]
btw why do you do: `gem "sidekiq", require: false` why don you just remove `require: false`?

**Comment by HoneyryderChuck** [comment]
Because I don't need sidekiq in all the processes I'm bootstrapping. It's a techniche for minimizing early memory allocation and improve process start time.

**Comment by ondrejbartas** [comment]
Ok good point ;)

**Comment by ondrejbartas** [comment]
@HoneyryderChuck Hi, sorry for delay, I just released `0.6.3` which impolements require on correct place

**Comment by HoneyryderChuck** [comment]
Great :) I already moved on from that project, but others can take advantage, hopefully

**Comment by HLFH** [comment]
@HoneyryderChuck So, which gem are you now using for that purpose?

**Comment by HoneyryderChuck** [comment]
I moved on from the project using your gem, I meant. I don't have the need for sidekiq crons in my current one. Will gladly reuse and test if I ever need it again.

**Comment by ondrejbartas** [comment]
@HoneyryderChuck glad to hear.
