### ISSUE TITLE
How to process scheduled jobs any time soon, ignoring scheduled time

### ISSUE THREAD

**Issue by knzudgt** [ondrejbartas/sidekiq-cron#131]
I just finished to configure my Rails application with Sidekiq and Sidekiq-Cron for background jobs, and launched successfully Sidekiq from the root of my application.

Since some jobs were expected to be processed earlier, before I started Sidekiq, I would like to know if (and how) can they be enqueued and processed at any time, bypassing Cron scheduled time.

In particular, I noticed the web UI for Cron Jobs offers the opportunity to enqueue jobs at any time: will they be processed as soon as they are enqueued or will they be processed at the expected scheduled time?

**Comment by ondrejbartas** [comment]
Hi Sidekiq-Cron is adding new jobs to queue in time which matched CRON tab.

So if you need to process/enqueue some job manulaly you can call YourWorker.perform_async() and use original Sidekiq methods for it. 

In Cron UI you can click on enqueue now which will add job to queue after pressing button, so if you have worker on that queue, it will get processed by normal sidekiq.
