### ISSUE TITLE
Crons are not always scheduled with many sidekiq processes

### ISSUE THREAD

**Issue by Connorhd** [ondrejbartas/sidekiq-cron#132]
Sidekiq slows down its polling based on the number of processes by default. This means that if the polling threads on multiple processes happen to align there can be a gap of up to 15 seconds * number of processes + 50%. See the logic here https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/scheduled.rb#L102

The result of this is there can be a gap of more than 1 minute in checking for crons to schedule and crons can be missed.

This can be worked around by setting the average_scheduled_poll_interval option, but sidekiq-cron should probably override this polling logic to ensure crons are checked at least once per minute.

**Comment by ondrejbartas** [comment]
#156

**Comment by ondrejbartas** [comment]
released in 0.6.0
