### ISSUE TITLE
Empty/Commented out .yml file causes sidekiq to not boot

### ISSUE THREAD

**Issue by cmalpeli** [ondrejbartas/sidekiq-cron#135]
It appears that having all your jobs commented out in your schedule.yml file causes Sidekiq not to boot up properly thus simply building up your queue of jobs.

**Comment by ondrejbartas** [comment]
I will look into this. But that is strange, it should normally work

**Comment by ondrejbartas** [comment]
Btw better than commenting out all cons is to comment out the line which is loading jobs 👍
