### ISSUE TITLE
sidekiq 5 compatibility ?

### ISSUE THREAD

**Issue by harold-s** [ondrejbartas/sidekiq-cron#138]
Hello,
Do you have any ides if this gem is or will be compatible with Sidekiq 5 ?
https://github.com/mperham/sidekiq/blob/5-0/5.0-Upgrade.md

Thanks !

**Comment by ondrejbartas** [comment]
@harold-s Hi i think it should work, it is not using delay queues.  It is adding them directly to queue
pls let me know if it work or not 👍

**Comment by harold-s** [comment]
Thanks @ondrejbartas . We have to move out from sidetiq (incompatible with new Sidekiq) so just making sure we could use sidekiq-cron. We'll test it in the next couple of weeks and I'll let you know !

**Comment by Dorian** [comment]
@harold-s 👍 Same, just migrated from sidetiq, much better actually, especially the web interface

**Comment by ondrejbartas** [comment]
@Dorian thanks 👍
