### ISSUE TITLE
Enqueue via web backend is enqueuing jobs with wrong timezone

### ISSUE THREAD

**Issue by lichtamberg** [ondrejbartas/sidekiq-cron#142]
Everytime I enqueue a job in the backend, I can see that the next schedule is in about an hour (59 minutes) - which is wrong (should be queued immediately, not in one hour duration).

As far as I know, you specify the enqueuing time by calling Time.now in your job.rb (which gives back a time in the current time zone) - but somehow this is not matching as it seems (our server is running +0100, rails itself is configured to use UTC).

Shouldn't this be Time.zone.now in your job.rb?
Do you have n hint for me? 
Please correct me if I'm wrong!

**Comment by lichtamberg** [comment]
I've attached a screenshot here.. You can see that the job should run each minute, but is enqueued 1 hour too late :)

![bildschirmfoto 2017-03-22 um 10 52 43](https://cloud.githubusercontent.com/assets/10075/24191972/bfd4a3f6-0eed-11e7-8d1f-a3418b77647d.png)

**Comment by ondrejbartas** [comment]
released new version 0.5.0 and btw thanks for fix

**Comment by lichtamberg** [comment]
You are welcome :)
