### ISSUE TITLE
Feature request: Add "delete all" button to planned tab

### ISSUE THREAD

**Issue by lichtamberg** [ondrejbartas/sidekiq-cron#143]
At the moment there is only a button for deleteing the selected jobs on the "planned" tab. Could you maybe add another button where I can delete all planned jobs?

**Comment by ondrejbartas** [comment]
I have added action buttons for enque, enable, disable & delete all jobs.

**Comment by ondrejbartas** [comment]
released in 0.6.0

**Comment by lichtamberg** [comment]
Supercool, thanks!
