### ISSUE TITLE
Ability to run a job at specific time once

### ISSUE THREAD

**Issue by dmitrypol** [ondrejbartas/sidekiq-cron#146]
https://github.com/Moove-it/sidekiq-scheduler has an interesting feature where you can specify   `at: '3001/01/01'`.  The underlying rufus-scheduler supports that but after looking at sidekiq-cron there does not seem to be a way to configure it.  

Has anyone tried doing that?  

One use case for this is scheduling a job to run far in the future and then using "Enqueue Now" button to run jobs on demand.

**Comment by ondrejbartas** [comment]
you can specify one time per year at maximum. Otherwise it would be better for you to create rake task which you will run manually :D.

What do you think?

**Comment by dmitrypol** [comment]
It could work for some use cases.  My goal was to give biz users ability to run certain jobs via GUI.  I am now looking into https://github.com/richfisher/sidekiq-enqueuer.  If that does not work I can build a GUI myself but I was hoping to use something off the shelf.

**Comment by ondrejbartas** [comment]
@dmitrypol 
<img width="1212" alt="screen_shot_2017-04-13_at_21_41_00" src="https://cloud.githubusercontent.com/assets/45809/25021290/f7bcdf3a-2091-11e7-9389-5155a63b93e8.png">

 you can disable job in UI but still enqueue it by button

**Comment by ondrejbartas** [comment]
when yíou disable job it will not be automatically enqueued 💃

**Comment by dmitrypol** [comment]
Ah, that is a good idea. Thanks for suggestion.
