### ISSUE TITLE
Scheduled jobs sometimes don't run

### ISSUE THREAD

**Issue by jpserra** [ondrejbartas/sidekiq-cron#147]
Hi @ondrejbartas 

I have been struggling with this issue for a while now. When we have a bunch of scheduled jobs (various different `crons`) It happens that randomly some jobs don't run. 

When looking into the `Job` class, I found [this](https://github.com/ondrejbartas/sidekiq-cron/blob/master/lib/sidekiq/cron/job.rb#L546) line that I seem to be struggling to understand.

My question is, shouldn't the hardcoded `60` seconds used in `not_past_scheduled_time?` method be the cron period (in seconds) of that particular job instead?

I have seen a lot of forks that the only thing they do is remove the `not_past_scheduled_time?` validation so I believe there's several people with the same issue so It'd be great if you could clarify this.

Thank you!

**Comment by ondrejbartas** [comment]
@jpserra Hi, which version of sidekiq do you use? It can depends on some logic of poller and intervals

**Comment by jpserra** [comment]
I'm using sidekiq-cron (0.4.5) and sidekiq  4.2.10 and i still get ser some jobs not getting enqueued when they're supposed to because the poller takes foo long to check all jobs (more than 60s) causes the problem

**Comment by ondrejbartas** [comment]
@jpserra how many jobs you have?

**Comment by ondrejbartas** [comment]
the whole process of checking enquation of jobs should take jus miliseconds

**Comment by ondrejbartas** [comment]
try to set: `Sidekiq.options[:poll_interval_average]` to 30s

**Comment by ondrejbartas** [comment]
Sidekiq in newer versions changed way how they schedule jobs based on number of workers a some magic

**Comment by jpserra** [comment]
Hi @ondrejbartas 

I start having this issue when I have around 4k jobs scheduled for the same cron.

This is not something necessarily related to sidekiq latests versions, I was having the same issue with `sidekiq-cron (0.4.2)` and `sidekiq (4.1.4)` but since that polling logic was already present in 4.1.4 I'll give that a try, thanks!

**Comment by jpserra** [comment]
Changing Sidekiq's `poll_interval_average` didn't solve the problem either. The only way i manage to have all my schedules enqueued is either adding more dynos or simply removing the `not_past_scheduled_time?` since the issue is that it takes more than `60` seconds to enqueue all the 4k jobs. 

Do you foresee any unexpected behaviour if that verification is removed?

**Comment by ondrejbartas** [comment]
@jpserra I am thinking, can you share which sidekiq cron 3rd parts gems are you using (uniq jobs etc?) Maybe enqueue can be slow because of some checks. 

I have updated code in master so it will remember time for enqueue of all jobs in one run. So this maybe can solve problem. Pls can you test it from master?

**Comment by ondrejbartas** [comment]
@jpserra checkout #152.

I added test which enqueues 10 000 jobs in 27s. That is ok (370jobs/s)

**Comment by ondrejbartas** [comment]
#153 now it is 19s for 10 000.

**Comment by jpserra** [comment]
Hi @ondrejbartas !

First of all, thank you for addressing this issue in such a fast manner, it's been of great help!

I've tested the latest version of the gem and indeed the problem is fixed, all jobs get enqueued when their cron is due so everything looks great!

**Comment by ondrejbartas** [comment]
@jpserra I am glad I could help and sidekiq-cron is doing job for you 👍

**Comment by zainrafique** [comment]
Hi @ondrejbartas 
I am using sidekiq 4.0.2 and sidekiq-cron 0.4.3. I have the same issue. My schedule.yml is here
wta_forecast_fetch_job:
  cron: "0,30 * * * *"
  class: "WtaForecastSchedulerWorker"
  queue: reports_scheduler
  description: "This job fetches data "

Sometimes my cron job does not run. I also have tried this on sidekiq 3.5.1 and sidekiq-cron 0.3.0.
can you guide me in right direction?

**Comment by ondrejbartas** [comment]
@zainrafique Can you update sidekiq and sidekiq-cron to latest version and test it?

Also make sure that your sidekiq process is running all the time. Also make sure that you are not clearing redis database. 

You can check Sidekiq log, because sidekiq cron is putting there some log information.
Look for
"enqueued #{@name}: #{@message}"` but be aware it is Debug, so if you are not storing this level of logs on productino, turn it on so you will se what happens. 

Sidekiq-Cron is nor responsible for running jubs, it adds them to queue and sidekiq then pick them and executes them.

Please let me know about your progress

**Comment by zainrafique** [comment]
Thanks for the response.
Yes, I can update sidekiq and sidekiq-cron to the latest version.
I have checked sidekiq logs. There is no entry for missing jobs.  I think sidekiq-cron is not adding them to queue.

**Comment by ondrejbartas** [comment]
It is in debug mode, so maybe they are not recorded at all...
