### ISSUE TITLE
Change log is not up to date

### ISSUE THREAD

**Issue by tmikoss** [ondrejbartas/sidekiq-cron#157]
At the time of writing, the current release is 0.6.0, but Changes.md lists 0.4.0 as latest.

**Comment by ondrejbartas** [comment]
Thanks for pointing it out :( I totally forgot about that file 🗡 
https://github.com/ondrejbartas/sidekiq-cron/commit/7a801ed6c792d08794884d6d7db0c0d674eec7d1

can I close it?

**Comment by tmikoss** [comment]
Thank you!
