### ISSUE TITLE
Using sidekiq-cron with rails engine and adding crons from multiple files

### ISSUE THREAD

**Issue by myjoytou** [ondrejbartas/sidekiq-cron#160]
Hi, I have an app as well as a rails engine. Both are having some crons which I need to put in sidekiq cron. But currently when I am using 
```ruby
Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_file)
```
from both places, the last one which gets loaded overwrites the previous one. Is there any way of appending crons, or I am doing it in a wrong way?

**Comment by ondrejbartas** [comment]
`Sidekiq::Cron::Job.load_from_hash` should not override prevously generated crons 

There is one catch cron jobs need to have uniq name, so ensure that your two files has different cron names.

Also what you can do is: 
```
schjedule1 = YAML.load_file(schedule_file)
schedule2 = YAML.load_file(schedule_file2)
Sidekiq::Cron::Job.load_from_hash schedule1.merge(schedule2)
```

On other hand with bang! `Sidekiq::Cron::Job.load_from_hash!` it is doing diff and removing missing ones.
