### ISSUE TITLE
Suggestion: Add Rake and Capistrano tasks?

### ISSUE THREAD

**Issue by berfarah** [ondrejbartas/sidekiq-cron#161]
Hi!

I wanted to see if there is any interest in adding Rake and Capistrano tasks to this library. I understand that these may not be features you'd want to maintain, so I've taken the liberty of creating an implementation for my company's own use:

https://github.com/coverhound/sidekiq-cron-tasks

The implementation currently does the following:

- Adds a `rake sidekiq_cron:load` that loads from a `config/sidekiq_cron.yml` file
- Adds a capistrano task that depends on Rails (for the rails environment), runs after deploy completion (I can see this being something you'd want to be different)
- Prefixes tasks that are loaded in via the rake task with `sidekiq_cron`
- Allows for configuration of both config file location and prefix

Please let me know if this is something you'd like me to port over. I'd be happy to decouple this from Rails (with the option to add Rails-specific dependencies).

Please let me know if you're interested and give me feedback if there are areas of the code you'd like to change.

**Comment by ondrejbartas** [comment]
@berfarah Love this idea and thank you for this. I would prefer these tasks to be part of separate gem. So it is ok. Can you add me as contributor to it? I don't need to change anything but maybe in future would be good for me to have access to it.

**Comment by ondrejbartas** [comment]
https://github.com/ondrejbartas/sidekiq-cron/commit/c69d6f59e550e4292e6c8d29f37cb4d8c6431bbe

**Comment by berfarah** [comment]
I've added you as a contributor - though PRs to master need approval + passing CI (part of our internal process)
