### ISSUE TITLE
Correct version number

### ISSUE THREAD

**Issue by knzudgt** [ondrejbartas/sidekiq-cron#167]
I notice that in the `readme.md file`, updated 2 months ago, you advise to install redis as follows:

    gem "sidekiq-cron", "~> 0.4.0"

However at rubygems.org the last version results the 0.6.3 of June 20, 2017. Thus it is suggested to install the gem in the Gemfile as follows:

    gem 'sidekiq-cron', '~> 0.6.3'

What is the correct version fo a Rails 5.0.0.1 application?

**Comment by ondrejbartas** [comment]
@knzudgt thanks for pointing this out, totally forgot about that in readme 😢 

I just updated readme. 

for 5+ rails app use `0.6.3`
