### ISSUE TITLE
README: "Adding cron job" is controversial

### ISSUE THREAD

**Issue by dadooda** [ondrejbartas/sidekiq-cron#174]
Hey team,

Reading this: https://github.com/ondrejbartas/sidekiq-cron#adding-cron-job can, **and I know it does**, incentivise inexperienced developers add calls to `Sidekiq::Cron::Job.create` directly to their worker classes.

I know it since I saw some doing this.

And this is bad. Although it may pretend to "just work", it'll effectively render performing external, potentially destructive filesystem actions **upon Ruby file inclusion**, which is bad, bad design. For instance, you run tests or code coverate, worker file gets included and BAM! some files get edited on the filesystem.

I posting this as an issue, not making a pull requst, since I want to exlain it systematically and want us come to a systematic solution.

Options, best to worst:

1. Remove controversial passage, add a meaningful chapter answering the question "How do I make my worker run every 5 minutes?". Actions: 1, 2, 3...
    * That's basically what 95% code bashers are looking for. **They are not looking for explanations, they look for passage they'll blindly copy and paste.** Let's give them one, but let it be a **correct one**.
2. Split controversial passage into two, say: "Suppose we have a worker like this: `(...)`". In order to make it run every 5 minutes, do this and this **in a separate file**, for example here's a rake task: `(...)`.
3. Keep controversial passage, supply a warning below it, like "DON'T ADD `Job.create` TO YOUR WORKER CLASS FILE, THIS IS JUST AN EXAMPLE". This is the worst option since it doesn't give guidance how to achieve the goal correctly. But it could at least make some look for solutions themselves.

Cheers!
Alex

**Comment by Akhilesh05** [comment]
Hello @dadooda 
I agree with you.
I suggest correcting the `README.md` and making a PR.
