### ISSUE TITLE
Determine the next time a job will run?

### ISSUE THREAD

**Issue by mikebaldry** [ondrejbartas/sidekiq-cron#177]
Is it possible to determine when a job will next be run? I've had a look at `Sidekiq::Cron::Job` but can't see any way to find that out. Looks like there is a way in Rufus but it isn't exposed.

Thanks for your work!

**Comment by ondrejbartas** [comment]
Hi

```
cron = Rufus::Scheduler::CronLine.new(Sidekiq::Cron::Job.all.first.cron)
cron.next_time(Time.now.utc).utc
```
