### ISSUE TITLE
Scheduled tasks are not enqueuing

### ISSUE THREAD

**Issue by chadwtaylor** [ondrejbartas/sidekiq-cron#179]
We just migrated over from `sidetiq` to `sidekiq-cron` to take advantage of Sidekiq's latest version. 

In our development environment, everything worked as expected. Jobs were enqueued according to the cron instructions. 

However, when we pushed it to Heroku, we could see the list of cron jobs but they are not enqueuing on schedule. I have to manually enqueue each job, which works. 

Any idea why it is not enqueuing based on the cron instructions?

sidekiq: 5.0.5
redis: 4.0.1
sidekiq-cron: 0.6.3

See attached screenshot:

<img width="545" alt="screenshot 2017-12-07 09 14 11" src="https://user-images.githubusercontent.com/350337/33719759-ce364b3e-db2f-11e7-8c09-1633fb300e43.png">

Any help and insight are appreciated.

**Comment by Onumis** [comment]
I have the same problem.

**Comment by Onumis** [comment]
After reading through https://github.com/ondrejbartas/sidekiq-cron/issues/80
I was able to notice a syntax error.

@ondrejbartas 
Would be nice for `Sidekiq::Cron::Job.load_from_hash!` to fail hard, instead of adding a string to the results: `["'cron' -> *0 2 * * *: cannot parse \"*0\""]`

**Comment by ondrejbartas** [comment]
@Onumis good point I will try to add this check to load from hash.
