### ISSUE TITLE
Unscheduled yet triggerable jobs

### ISSUE THREAD

**Issue by baburdick** [ondrejbartas/sidekiq-cron#186]
In Sidetiq (RIP), we were able to have an unscheduled job appear in the UI list with a button to trigger it manually. How is that done in the sidekiq-cron world?

(We've switched to sidekiq-cron and are happy, apart from this issue.)

**Comment by ondrejbartas** [comment]
Hi in web ui of sidekiq cron you can disable wanted job and then you have enqueue button to get it to queue

**Comment by baburdick** [comment]
@ondrejbartas: Thanks for your response!

Does this mean it has to have a valid cron schedule? Or can that be empty or nil? If it must have a valid cron schedule, what's the best practice for disabling such a job programmatically at startup? (Failing to disable it manually would be catastrophic.) And is there any way to hide the button to re-enable it, once it's been disabled?

**Comment by ondrejbartas** [comment]
@baburdick It needs to have valid cron line, but you can create job with `status: 'disabled'` and it will make sure that job will not be enqueued by cron.
<img width="1324" alt="screen_shot_2018-02-21_at_21_22_57" src="https://user-images.githubusercontent.com/45809/36503476-88a8cb6e-174d-11e8-8b12-0de53773411d.png">
