### ISSUE TITLE
Stopped queuing jobs

### ISSUE THREAD

**Issue by ramontayag** [ondrejbartas/sidekiq-cron#187]
We saw an instance where Sidekiq continued processing jobs like the ones that were added by the application itself, but sidekiq-cron stopped queuing new jobs. Restarting the sidekiq instance fixed this. However, next time this happens, what do you suggest we check out to see why this may have occurred?

**Comment by ramontayag** [comment]
Looking at the logs, I think I know what happened. There was a system restart and Redis was still down while Sidekiq had already booted up. I think that sidekiq-cron attempted to write the schedule into Redis, but failed.

Does this make sense? I didn't take too close a look at the sidekiq-cron code to see. The only thing I can think of improving is making sidekiq-cron retry and finally raise an error after N failed attempts.

**Comment by ondrejbartas** [comment]
@ramontayag this can happen, but when you look at https://github.com/ondrejbartas/sidekiq-cron/blob/master/lib/sidekiq/cron/poller.rb then you will see that both `def enqueue` and `def enqueue_job(job, time = Time.now.utc)` that it should correctly rescue from any problem.

I checked Sidekiq code base and it works similary as Sidekiq's Scheduler Poller so I can't tell you why sidekiq was correctly working after redis booted up and why Sidekiq Cron didn't :(

**Comment by ramontayag** [comment]
@ondrejbartas thanks for the response! I think I expected sidekiq-cron to raise an error, but I see now why it doesn't. I think this is the one sidekiq-cron logs:

![logs](https://user-images.githubusercontent.com/25332/36516958-43abe71c-17bb-11e8-94d2-d4cdcfd357f0.png)

I'll close this so it doesn't stay open forever. We'll attempt to recreate this in the future. Sometimes, we restart all our Kubernetes pods and it might mean the Redis pod is down when the sidekiq worker boots up. That is what happened the last time.

Cheers
