### ISSUE TITLE
Job did not get dequeued/removed when removed from YAML file

### ISSUE THREAD

**Issue by sirdharma** [ondrejbartas/sidekiq-cron#192]
Hello,

We had a Sidekiq job that was scheduled in Sidekiq through sidekiq-cron. We pushed a new version of the cron YAML file with the job removed, and surprisingly the job not only was still ran, but is also still marked as "enabled" in the web UI.

I thought sidekiq-cron used polling to know which job to run, so I am wondering why the job was ran when it was not present in the cron file any more.

How could we have prevented that? And how should we remove the job that still shows up in the UI (despite having been removed from the cron file)?

Thank you for your very useful gem and your time!

**Comment by lmansur** [comment]
How are you loading the new list of jobs?

If you load with `.load_from_hash!` (notice the bang) or `.load_from_array!`, it should remove stale jobs.

**Comment by sirdharma** [comment]
@lmansur Thank you for your answer. You are right, we use the non-bang version of `.load_from_hash`. I apologize if this is documented somewhere. If not, I think it’d be a great addition because we thought this behavior to be unexpected and quite misleading.

**Comment by sirdharma** [comment]
@lmansur Just found it in the documentation! My apologies, I’ll close the issue. Thank you for your time!
