### ISSUE TITLE
Cron jobs Redis key isn't unique per-application

### ISSUE THREAD

**Issue by jaredcwhite** [ondrejbartas/sidekiq-cron#195]
I'm using sidekiq-cron for multiple applications at once on my development machine, and I've run into a collision issue due to the fact that the Redis key for the set (as determined by `Sidekiq::Cron::Job.jobs_key`) is simply "cron_jobs". I found this out because one of my applications uses a different default time format from the others.

I think this should be configurable (either manually or automatically) so that it's unique per Rails application (for example: "my_rails_app_cron_jobs"). I'm going to go ahead and monkey patch this in my applications, but if you want me to work on a more viable solution and submit a PR, I'm happy to do so.

**Comment by jaredcwhite** [comment]
FYI, this is how I ended up doing the monkey patch in my config/sidekiq.rb initializer:

```ruby
Sidekiq::Cron::Job.class_eval do
  def self.jobs_key
    "#{Rails.application.class.parent_name.underscore}_cron_jobs"
  end
  def self.redis_key name
    "#{Rails.application.class.parent_name.underscore}_cron_job:#{name}"
  end
  def self.job_enqueued_key name
    "#{Rails.application.class.parent_name.underscore}_cron_job:#{name}:enqueued"
  end
end
```

**Comment by ondrejbartas** [comment]
@jaredcwhite I know about this problem

I solved it in my development machine to setting different databases for every application (basically same what you do with PG for example - database name)

Redis has 16 database by default configuration so it would be easier to change just config

`redis://127.0.0.1:6379/1`, `redis://127.0.0.1:6379/2`, `redis://127.0.0.1:6379/3`...
