### ISSUE TITLE
Removing workers from schedule.yml

### ISSUE THREAD

**Issue by asoong** [ondrejbartas/sidekiq-cron#196]
Is removing the entry in `schedule.yml` supposed to deactivate/remove the job? Or do I have to go through the console/dashboard?

**Comment by ondrejbartas** [comment]
@asoong 
It dependes how you use it:

```
Sidekiq::Cron::Job#load_from_hash hash
Sidekiq::Cron::Job#load_from_array array
```
will just update or add new jobs

but:
```
Sidekiq::Cron::Job#load_from_hash! hash
Sidekiq::Cron::Job#load_from_array! array
```
wil update or add new jobs and also delete all jobs that are not in hash/array
