### ISSUE TITLE
why i cannot send the from sidekiq cron?

### ISSUE THREAD

**Issue by dunods** [ondrejbartas/sidekiq-cron#198]
why i cannot send mailer through sidekiq cron 

![image](https://user-images.githubusercontent.com/8032766/39752654-4c5bc9e8-52e6-11e8-943f-f5e6d37739c4.png)
it was in cron list but it stay in enque

![image](https://user-images.githubusercontent.com/8032766/39752705-73217b2c-52e6-11e8-91f9-5d08af14aebe.png)

any solutions?
im using aws elasticache as my redis server.

**Comment by ondrejbartas** [comment]
Hi you need to have worker running on queue `universal_worker` or change setup of your sidekiq cron to `"queue": "default"`
