### ISSUE TITLE
Incompatible with newer versions of rufus-scheduler

### ISSUE THREAD

**Issue by JamesChevalier** [ondrejbartas/sidekiq-cron#199]
This gem works with [rufus-scheduler](https://github.com/jmettraux/rufus-scheduler) version 3.4.2 but does not work with version 3.5.0

While using version 3.5.0, attempting `Sidekiq::Cron::Job.create` calls returns `false`, and the job is not added.

My only guess to the cause is that according to the [changelog](https://github.com/jmettraux/rufus-scheduler/blob/master/CHANGELOG.txt), rufus-scheduler now uses [fugit](https://github.com/floraison/fugit) to parse durations and cronlines.
I looked for instances of `parse_time_string` and `parse_duration_string` in this repository, and didn't find any - so it doesn't appear that their removal is playing a part here.

**Comment by jmettraux** [comment]
Hello @JamesChevalier,

I am the author of rufus-scheduler.

> While using version 3.5.0, attempting Sidekiq::Cron::Job.create calls returns false, and the job is not added.

Would you have time to instrument a bit the following method in Sidekiq-Cron and tell me why it returns false?

https://github.com/ondrejbartas/sidekiq-cron/blob/master/lib/sidekiq/cron/job.rb#L393-L412

I'm particulary interested in what gets stuffed into `@errors` and what `Exception` gets intercepted (stacktrace and all).

I don't have any Sidekiq (nor Redis) instance at hand, thanks in advance!

**Comment by brianstien** [comment]
@jmettraux This problem is affecting us as well. I was able to track down the error you were looking for

```
jruby-9.1.12.0 :018 > j = ::Sidekiq::Cron::Job.new(:name => "foo", :cron => "* * * * *", :klass => "Foo", :queue => "foo")
 => #<Sidekiq::Cron::Job:0xd332ebc @active_job=false, @active_job_queue_name_prefix=nil, @active_job_queue_name_delimiter=nil, @klass="Foo", @args=[], @status="enabled", @last_enqueue_time=nil, @fetch_missing_args=true, @message={"queue"=>"foo", "class"=>"Foo", "args"=>[]}, @name="foo", @queue="foo", @queue_name_with_prefix="foo", @cron="* * * * *"> 
jruby-9.1.12.0 :019 > j.valid?
 => false 
jruby-9.1.12.0 :020 > j.errors
 => ["'cron' -> * * * * *: uninitialized constant Rufus::Scheduler::CronLine"]
```

**Comment by jmettraux** [comment]
@brianstien Thanks a lot!

I submitted a pull request that aligns Sidekiq-cron on fugit (the parsing lib behind rufus-scheduler >= 3.5 instead of rufus-scheduler).

http://jmettraux.skepti.ch/20180515.html?t=rufus_scheduler_3_5_0_released

**Comment by ardation** [comment]
I got around this by adding this to my Gemfile

```
gem 'rufus-scheduler', '~> 3.4.0'
```

**Comment by jmettraux** [comment]
Yet another reminder: https://bundler.io/v1.16/guides/updating_gems.html

**Comment by giedriusr** [comment]
Any news?

**Comment by dcdieci** [comment]
I just installed version 1.0.0 and it fixed the mentioned error for me

**Comment by giedriusr** [comment]
I tried installing new version, but for me, cron jobs can't start. Anyone else?

**Comment by davidhrbac** [comment]
Upgraded to 1.0.0 and it seems to fix the issue.

**Comment by jmettraux** [comment]
@ondrejbartas Could you please close this issue and also its duplicates: gh-201 and gh-206?

**Comment by lucascaton** [comment]
After upgrading to version `1.0.0`, although it solved the problem, `Last enqueued` column got stuck and always displays `10 hours ago`. However, the logs show that it's running every hour as expected.

Is anyone else having this issue?

![image](https://user-images.githubusercontent.com/86755/42974490-d8f25e10-8bfa-11e8-809b-5941610bb8eb.png)

**Comment by jmettraux** [comment]
@lucascaton Yes, people are giving feedback and coming with suggestions at gh-202, gh-209, gh-210, and gh-213. Since it's not related to "Incompatible with newer versions of rufus-scheduler" (this issue), the conversation is happening elsewhere.

**Comment by lucascaton** [comment]
Thanks :)

**Comment by taki** [comment]
If it seems to be corrected, could you please close this issue.
