### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by cassiopagnoncelli** [ondrejbartas/sidekiq-cron#201]
I have been using sidekiq-cron successfully over the past few months, now it stopped working overnight. Not yet aware why. Tasks are there, should be executed, but they won't.

<img width="1271" alt="screen shot 2018-05-19 at 1 02 34 am" src="https://user-images.githubusercontent.com/4023526/40264721-065dfd4e-5b01-11e8-95bc-7b42c0146532.png">

Anyone can shed a light?

**Comment by Arie** [comment]
Same thing happened to me when I upgraded to 3.5.0, I've downgraded to 3.4.2, which works.

**Comment by vanitu** [comment]
+q

**Comment by vanitu** [comment]
+1 same issue. Stop working after version update.

**Comment by skk2010** [comment]
+1 the same for me

**Comment by cassiopagnoncelli** [comment]
Thanks guys, with your help I could find a running configuration

- Ruby 2.5.0
- Rails 5.2.0
- Sidekiq 5.1.3
- Sidekiq cron 0.6.3

**Comment by vanitu** [comment]
Issue related to #199 
We found a temporary fix by adding rufus-scheduler to our gem file with fixed version.

gem 'rufus-scheduler', '~> 3.4.0'

Hope pull_request will be soon updated

**Comment by cassiopagnoncelli** [comment]
3.4.2 is the latest working version

**Comment by ondrejbartas** [comment]
Hi guys sorry for delay, new version v1.0.0 should fixed that problem

**Comment by Onumis** [comment]
Yes and please push this forward to: https://github.com/ondrejbartas/sidekiq-cron/pull/218
