### ISSUE TITLE
Setting the last_enqueue_time for a job can be ambiguous in format

### ISSUE THREAD

**Issue by alecjacobs5401** [ondrejbartas/sidekiq-cron#202]
`Sidekiq::Cron::Job#save_last_enqueue_time` just passes the `@last_enqueue_time` to `hset` for the redis connection, which is calling `to_s` on the `Time` object.

If you're using a non-standard default string format for Time objects, then parsing the `last_enqueue_time` will raise with the following error:

```
ArgumentError: Ambiguous parse format
```

Edit: Actually looks like this was fixed in the master branch..but not updated in any of the release versions. Any updates?

**Comment by ondrejbartas** [comment]
@alecjacobs5401 this is fixed in v1.0.4

**Comment by ondrejbartas** [comment]
please close it if it is resolved

**Comment by alecjacobs5401** [comment]
@ondrejbartas 

Thanks!
