### ISSUE TITLE
Changes and readme are outdated

### ISSUE THREAD

**Issue by giedriusr** [ondrejbartas/sidekiq-cron#207]
Why new version has been released and Changes.md and Readme was not updated?

**Comment by tisba** [comment]
From what I can tell of https://github.com/ondrejbartas/sidekiq-cron/compare/6a01bd1740b010358f34a851c7ddc0d5227a4c76...b215aa2abfabc1ca31372770c72738667f1703cf the changes don't look like breaking changes (assuming that `sidekiq-cron` follows semver). It looks like cleanup, a bit refactoring, updating of tooling and tests.

Maybe 1.0 got pushed to Rubygems by accident. In any case, take your time to get the release right, @ondrejbartas 💕 :)

**Comment by railsbros-dirk** [comment]
The update to 1.0 was super easy, hadn't any problems at all. Thanks for the work on this @ondrejbartas 💕

**Comment by tisba** [comment]
We did the update as well and also did not had any issues 👍

**Comment by tisba** [comment]
In case someone is following this, the recently released 1.0.1 only contains one commit: https://github.com/ondrejbartas/sidekiq-cron/commit/a963b7269a61282dd73d35ca7bfaeb407d2bc4ef (merge of #210).

**Comment by ondrejbartas** [comment]
Hi I have updated changelog. Is it ok like this?

**Comment by tisba** [comment]
Thanks @ondrejbartas. I think the README is still a bit outdated, but the changelog is fine for me.

The irritating factor was the major version bump without any information, what could break. For me, and maybe others, this makes one feel a bit uneasy when thinking about upgrades.

Again, thanks for the changelog update!

**Comment by ondrejbartas** [comment]
@tisba I added one warning block for upgrade from 0.6.X to 1.0.X

is it better?

**Comment by tisba** [comment]
Yep! There are more references in the README that appears to be outdated, but I'm happy to provide a PR if you like.

**Comment by ondrejbartas** [comment]
@tisba please I don't have so much time for this, so I will be grateful.

**Comment by giedriusr** [comment]
Thanks. I will close this now. @tisba will do the rest with the README. 👍
