### ISSUE TITLE
Is it possible to schedule/set a php script as a cron using sidekiq? if so, how?

### ISSUE THREAD

**Issue by RakibSohail** [ondrejbartas/sidekiq-cron#215]

**Comment by ondrejbartas** [comment]
@RakibSohail Hi this is not question for Sidekiq-Cron but mostly for Sidekiq itself. 

Sidekiq cron just adds jobs to queue when they should be added based on cron.
Sidekiq worker must be running to be able to do schedules and crons.

But I can tell you that I have big rails app with tens of Crons which runs ruby workers and in addition I am adding some jobs to different queue which is not handled by ruby sidekiq workers but by Elixir workers with support by `exq`.

So it is possible
