### ISSUE TITLE
Remove scheduled jobs from master list when they no longer exist

### ISSUE THREAD

**Issue by tubbo** [ondrejbartas/sidekiq-cron#216]
When scheduling cron jobs within a Ruby initializer like so:

```ruby
Sidekiq::Cron::Job.create(
  name: 'Foo',
  klass: 'FooJob',
  cron: '0/1 * * * *'
)

Sidekiq::Cron::Job.create(
  name: 'Bar',
  klass: 'BarJob',
  cron: '0/1 * * * *'
)
```

Removing the `Sidekiq::Cron::Job.create` call does not actually remove the job from `Sidekiq::Cron::Job.all`, however, and causes an error upon enqueuing a constant that no longer exists.

I propose that `Sidekiq::Cron::Job.all` exclude the worker classes that no longer exist, when iterating over `job_hashes`...

```ruby
next unless const_defined? h[:klass]
```

Is that an acceptable solution?

**Comment by cabello** [comment]
IMHO it should log when this case happens because something is referencing non-existing code, and this should be investigated and fixed it.

**Comment by ondrejbartas** [comment]
@tubbo When I am working with sidekiq from ruby directly then when I need to remove some code which is triggered by sidekiq cron then I am adding for some time for example in initializers of sidekiq

`Sidekiq::Cron::Job.destroy "Job Name"` which will ensure then removed code also gets removed from cron.

After production release I am removing this cleanup and thats it.

Remember, sometimes you can have for example GO taking care of some jobs so then it will not work for you.

**Comment by tubbo** [comment]
@ondrejbartas For most people, that is probably OK, but if you're trying to ship `Sidekiq::Cron::Job` classes as part of a Rails engine that doesn't work very well. That solution expects the downstream consumer of the engine to know exactly which jobs were removed or added between versions, which is not desirable.

That said, your example of using something like a [goworker](https://www.goworker.org/) to handle job execution definitely would make my solution undesirable. What if we had another method one could call in order to opt-in to this behavior, like `Sidekiq::Cron::Job.reset!`, which could be called upon initialization of the app if you know for a fact that your list of cron jobs is the "canonical" list.

Here's what I wanted to add to **Sidekiq::Cron::Job**:

```ruby
def self.reset!
  all.all?(&:destroy)
end
```

That would allow for the following code in an initializer:

```ruby
Sidekiq::Cron::Job.reset!

Sidekiq::Cron::Job.create(
  name: 'Foo',
  klass: 'FooJob',
  cron: '0/1 * * * *'
)

Sidekiq::Cron::Job.create(
  name: 'Bar',
  klass: 'BarJob',
  cron: '0/1 * * * *'
)
```

For those of us who want to control the list of cron jobs within our initializers, this at least us gives us the option to do so. I'm going to try the following code atop my initializer, because I think it'll fix the problem for us, and tell you how it goes!

```ruby
Sidekiq::Cron::Job.all.each(&:destroy)
```

(the claim could also be made that the `.reset!` method is unnecessary, and we could just document how to do this via the `.all.each(&:destroy)` syntax...)
