### ISSUE TITLE
Delayed Extension

### ISSUE THREAD

**Issue by mengqing** [ondrejbartas/sidekiq-cron#219]
Anyway to get this working with a class that uses delayed extension?

**Comment by ondrejbartas** [comment]
@mengqing Can you please give me more details? Example would be great.

**Comment by mengqing** [comment]
We use [Delayed extensions](https://github.com/mperham/sidekiq/wiki/Delayed-extensions) with service objects so that they can be called async / sync depending on use cases.

eg:

```
def FoobarService
  def self.call
    # do some work
  end
end

FoobarService.delay.call
```

Unfortunately I couldn't get this to work with the `sidekiq-cron` at the time of posting.

I did however managed to come up with a solution to work with our use cases.

```
module FakeWorker
  extend ActiveSupport::Concern

  included do
    def self.set(queue:)
      @default_queue = queue

      self
    end

    def self.perform(*args)
      call(*args)
    end

    def self.perform_async(*args)
      delay(*args, queue: @default_queue).call(*args)
    end
  end
end

def FoobarService
  include FakeWorker

  def self.call(*args)
    # do some work
  end
end
```

And now I can schedule this service like following

```
Sidekiq::Cron::Job.create(name: 'Foobar service - every 5min', cron: '*/5 * * * *', class: 'FoobarService')
```

Not sure if there is a better solution than this, but this is currently working for us
