### ISSUE TITLE
Getting 'Forbidden' on clicking 'Enqueue now'

### ISSUE THREAD

**Issue by mayuresh-srivastava** [ondrejbartas/sidekiq-cron#227]
Getting 'Forbidden' on clicking 'Enqueue now' in staging and production environment.

Using 'rails', '5.1.6', sidekiq-cron (1.0.4) which uses fugit (~> 1.1) and sidekiq (>= 4.2.1)

I can see from [60](https://github.com/ondrejbartas/sidekiq-cron/issues/60) and [61](https://github.com/ondrejbartas/sidekiq-cron/issues/61) that issue got resolved a long back but still getting same issue.

**Comment by mayureshmayur** [comment]
Yeah. Tried [https://github.com/mperham/sidekiq/wiki/Monitoring#forbidden](url) as well but no luck.

**Comment by mayureshmayur** [comment]
Yeah. Tried [this](https://github.com/mperham/sidekiq/wiki/Monitoring#forbidden) as well but no luck.

**Comment by phlegx** [comment]
Have you tried this?

```ruby
# config/routes.rb

require 'sidekiq/web'
require 'sidekiq/cron/web'
Sidekiq::Web.set :sessions, false
```

Described here: [github.com/mperham/sidekiq](https://github.com/mperham/sidekiq/wiki/Monitoring#sessions-being-lost)

**Comment by superchell** [comment]
`Sidekiq::Web.class_eval do
  use Rack::Protection, :except => :http_origin
end`

work for me
