### ISSUE TITLE
Elastic Beanstalk support

### ISSUE THREAD

**Issue by adolfopeccin** [ondrejbartas/sidekiq-cron#228]
Anyone is running this @ AWS Elastic Beanstalk?

We are using Sidekiq right now without problem, but when using Cron, all jobs stuck enqueued.

**Comment by feliperaul** [comment]
@adolfopeccin Adolfo, 2 questions: which tutorial did you follow in setting up Sidekiq with EBS? Also, did you manage to get this gem working with Elastic Beanstalk?

**Comment by tcd** [comment]
@adolfopeccin @feliperaul 
One question: Did either of y'all happen to get this working on EBS?

**Comment by feliperaul** [comment]
Unfortunately no...

Em sex, 4 de out de 2019 às 12:36, Clay Dunston <notifications@github.com>
escreveu:

**Comment by tcd** [comment]
@feliperaul I've managed to get it working on an EC2 instance, but not through EBS :/

**Comment by adolfopeccin** [comment]
@tcd @feliperaul Nope :( no luck yet, did you guys managed to get this working?
