### ISSUE TITLE
Jobs are being queued for each worker process (Heroku) 

### ISSUE THREAD

**Issue by jeffblake** [ondrejbartas/sidekiq-cron#233]
The docs say that this won't happen https://github.com/ondrejbartas/sidekiq-cron/pull/176

But I am getting the same jobs queued, usually within 3-10 seconds apart of each other.

<img width="1191" alt="screen shot 2018-12-07 at 10 51 00 am" src="https://user-images.githubusercontent.com/620564/49666981-77ba8a00-fa0e-11e8-9c71-61a5ad5ba3b3.png">

<img width="795" alt="screen shot 2018-12-07 at 10 52 06 am" src="https://user-images.githubusercontent.com/620564/49667021-9fa9ed80-fa0e-11e8-86e0-d32aaf9a87e0.png">

Also, shouldn't `*/15 * * * *` be queued every 15th minute? I'm getting at most 4 queued per day.

**Comment by ondrejbartas** [comment]
@jeffblake that log you are showing is logged when cron job is created in redis (not added to queue) https://github.com/ondrejbartas/sidekiq-cron/blob/3ffe31ad29a28aa55931557f5facbeaeabbff30b/lib/sidekiq/cron/job.rb#L466 

When you start worker/app and you have somewhere in your code add cron job or load jobs from array that will trigger that message, this is why it shows you multiple times in different days/hours/minutes.

Try to look for:

`enqueued abandon_orders` in your log

Does it make sense?
