### ISSUE TITLE
Cron jobs never starts

### ISSUE THREAD

**Issue by masudhossain** [ondrejbartas/sidekiq-cron#234]
I've been dealing with this issue for a few days now. It seems that the cron jobs are not executing at all (i've tried this on c9.io and also my local macosx machine). 

I cloned https://github.com/driftingruby/061-periodic-tasks-with-sidekiq-cron

and it doesn't seem to be starting the cron job at all (i tried whenever gem too, and ran into the issue of the cron jobs never starting in the first place). 
http://prntscr.com/lx7p15 

Am I missing some sort of cron setup or something?

**Comment by jmettraux** [comment]
Hello,

please upgrade sidekiq-cron in your project's Gemfile bundle. The project you cloned is using an old sidekiq-cron version with a newer rufus-scheduler version. If you `bundle update sidekiq-cron`, the versions will synchronize and the scheduling should happen normally.

Best regards.

**Comment by masudhossain** [comment]
@jmettraux this didn't fix it unfortunately 😞

**Comment by jmettraux** [comment]
@masudhossain what does your `Gemfile.lock` looks like now? Any error or dubious message appearing in the project's log?

**Comment by masudhossain** [comment]
@jmettraux 0 errors in logs and gemfile.lock now has `sidekiq-cron (1.0.05)`

**Comment by jmettraux** [comment]
@masudhossain what does your cron string looks like? Anything that could [help us help you](https://gist.github.com/jmettraux/310fed75f568fd731814)?

**Comment by ondrejbartas** [comment]
@masayukioguni have you loaded any cron jobs? https://github.com/ondrejbartas/sidekiq-cron#adding-cron-job

because from your screenshot it seems that you didn't add any. If you have `Sidekiq::Cron::Job.create(name: 'Hard worker - every 5min', cron: '*/5 * * * *', class: 'HardWorker')
` somewhere inside of your code, then this part of code needs to be loaded (not lazy loading as Rails does) otherwise it will not add cron job

**Comment by jeffutter** [comment]
I was seeing this as well after recently upgrading `sidekiq-cron` from `0.4.5` to `1.1.0`. The jobs would show up in the Sidekiq GUI, but look like this:

<img width="1217" alt="screen shot 2019-01-21 at 12 29 42 pm" src="https://user-images.githubusercontent.com/570037/51492701-5c1a0180-1d78-11e9-955f-9f2854065be2.png">

That one, for example, should run every two minutes, but hasn't run in 3 days.

I had been running sidekiq `4.2.10`. After upgrading Sidekiq to `5.2.5` it seems to be working again, perhaps there is some incompatibility between sidekiq `4.2.x` and `sidekiq-cron` `1.x`?

**Comment by sqlninja** [comment]
I am having a similar issue when using a schedule.yml file.
The cron jobs never start on their own (post deploy) until I enqueue them once manually

**Comment by masayukioguni** [comment]
@masudhossain https://github.com/ondrejbartas/sidekiq-cron/issues/234#issuecomment-455996519

I will forward it.

**Comment by collimarco** [comment]
I have a similar issue, maybe related: https://github.com/ondrejbartas/sidekiq-cron/issues/251

**Comment by tjozwik** [comment]
I had the same issue. Upgrading sidekiq to `5.1.3` and sidekiq-cron to `1.2.0` worked in my case.
