### ISSUE TITLE
Jobs don't appear in list

### ISSUE THREAD

**Issue by caplod** [ondrejbartas/sidekiq-cron#237]
I have sidekiq 5.2.5 and sidekiq-cron 1.1.0
The job (bill_due_invoices) from sidekiq-cron is running fine, but the dashboard shows no sign, it was excecuted. All entries are zero ?

![sidekiq-cron](https://user-images.githubusercontent.com/435070/51481035-fbe48900-1d92-11e9-8679-a6772af3ffac.png)

**Comment by shatle** [comment]
@caplod  can u get info?

**Comment by caplod** [comment]
Couldnt figure it out, so I switched to sidekiq-scheduler.
