### ISSUE TITLE
Deprecation warning from autoloading in initializer

### ISSUE THREAD

**Issue by hirowatari** [ondrejbartas/sidekiq-cron#249]
The readme.md seems to recommend doing the following:
```ruby
#initializers/sidekiq.rb
schedule_file = "config/schedule.yml"

if File.exist?(schedule_file) && Sidekiq.server?
  Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_file)
end
```
In Rails 6.0.0.rc1, this emits the following warning
```
 19:46 W  Rails -- DEPRECATION WARNING: Initialization autoloaded the constants PurgeJobLocationsFilesWorker, CalculateUsageForBillingPeriodWorker, and PurgeOldUsageRecordsWorker. -- These are the classes from schedule.yml

 Being able to do this is deprecated. Autoloading during initialization is going
 to be an error condition in future versions of Rails.

 Reloading does not reboot the application, and therefore code executed during
 initialization does not run again. So, if you reload SidekiqCronLoader, for example,
 the expected changes won't be reflected in that stale Class object.

 These autoloaded constants have been unloaded.

 Please, check the "Autoloading and Reloading Constants" guide for solutions.
  (called from <top (required)> at /prolo-rails/config/environment.rb:7)
```

Is there a new recommended way to do this?

**Comment by mrsweaters** [comment]
I'm also getting this issue in 6.0.0.rc2. I haven't found a workaround yet to satisfy the notice.

**Comment by majksner** [comment]
That is the error from the Rails 6 Zeitwerk autoloader.

**Comment by j15e** [comment]
You may move the load process to `Sidekiq.configure_server` configuration block, this way it won't be loaded when you run your development server (and this is not required).

**Comment by majksner** [comment]
@j15e For me it's already there. And the warning is still displayed.

```ruby
Sidekiq.configure_server do |config|
  config.redis = { db: ENV.fetch('REDIS_DB', 0) }
  Sidekiq::Cron::Job.load_from_hash!(Rails.configuration.cron_jobs)
end
```

**Comment by majksner** [comment]
Here is the fix.

Move your job(s) to `lib/cron_jobs/my_cron_job.rb` (lib outside of app folder in the root of rails project)

```ruby
# frozen_string_literal: true

module CronJobs
  class MyCronJob
    include Sidekiq::Worker

    def perform
      # your code
    end
  end
end
```


Last but not least. `config/initializers/sidekiq.rb`

```ruby
# frozen_string_literal: true

require_relative('../../lib/cron_jobs/my_cron_job')

cron_jobs = {
  my_cron_job: { cron: '0 4 * * *', class: 'MyCronJob', queue: 'cron' },
}

Sidekiq.configure_server do |config|
  Sidekiq::Cron::Job.load_from_hash!(cron_jobs)
end
```

**Comment by ecbypi** [comment]
I fixed this by loading the cron jobs in an `after_initialize` hook.  

```ruby
if Sidekiq.server?
  Rails.application.config.after_initialize do
    Sidekiq::Cron::Job.load_from_array \
      YAML.load_file(Rails.root.join("config", "scheduled-jobs.yml"))
  end
end
```

**Comment by megane42** [comment]
Rails warning message says:

```
In order to autoload safely at boot time, please wrap your code in a reloader
callback this way:

    Rails.application.reloader.to_prepare do
      # Autoload classes and modules needed at boot time here.
    end

That block runs when the application boots, and every time there is a reload.
For historical reasons, it may run twice, so it has to be idempotent.
```

so should we use `Rails.application.reloader.to_prepare do ... end` instead of `Rails.application.config.after_initialize do ... end` ?

**Comment by jeromedalbert** [comment]
Yes @megane42, I would go with the following as the more "official" way:

```ruby
#initializers/sidekiq.rb
schedule_file = "config/schedule.yml"

if File.exist?(schedule_file) && Sidekiq.server?
  Rails.application.config.to_prepare do
    Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_file)
  end
end
```

(thanks to @ecbypi for providing an initial working solution)

This is because the Rails docs regarding [autoloading when the application boots](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-when-the-application-boots) documents the usage of `Rails.application.config.to_prepare`. There is no mention of `after_initialize` and while both seem to work here, I would rather use the documented way.

What I have usually done to to migrate initializers that call application code under Zeitwerk autloading is to either `require` the files manually or use `Rails.application.config.to_prepare`. In the case of `sidekiq-cron` I prefer the latter since it will work effortlessly with an indefinite number of files and I don't have to know about their paths.

**Comment by ondrejbartas** [comment]
there is a new way to do it in 

```ruby
Sidekiq.configure_server do |config|
  config.on(:startup) do
    schedule_file = "config/schedule.yml"

    if File.exist?(schedule_file)
      Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_file)
    end
  end
end
```
