### ISSUE TITLE
sidekiq-cron 0.6.3 and rufus-scheduler

### ISSUE THREAD

**Issue by knzudgt** [ondrejbartas/sidekiq-cron#255]
I am developing a Ruby on Rails application and I would like to install `sidekiq-cron 0.6.3` (because it was working well in an old application). Now I am thinking if it might be convenient to use instead `1.0` because I read in the documentation that using older sidekiq-cron with `rufus-scheduler >= 3.5` "_ends up with jobs failing on creation_". 

How can I be sure I would end up using `rufus-scheduler < 3.5`?
I  imagine `rufus-scheduler` is installed by `sidekiq-cron`, so I suppose that `sidekiq-cron 0.6.3` would install `rufus-scheduler < 3.5`: is that correct?

**Comment by caecity43** [comment]
I got `NameError: uninitialized constant` and `NoMethodError: undefined method `jid='` errors when I upgrade to sidekiq-cron 1.1 for new jobs.

I try to clean redis (`Sidekiq.redis { |r| r.flushdb} `) and restart sidekiq, but not work.

please help.

**Comment by markets** [comment]
Since v1.0 this gem uses now Fugit: https://github.com/ondrejbartas/sidekiq-cron#upgrade-from--06-to-10
