### ISSUE TITLE
disable sidekiq-cron

### ISSUE THREAD

**Issue by mohsintahir** [ondrejbartas/sidekiq-cron#258]
I am running sidekiq in multiple server setup in production which means many sidekiq processes are running to process jobs. I have seen same job gets enqueued more than 1 time many times and I think it is due to the fact Sidekiq::Cron::Poller runs for each process and due to multiple processes are running, jobs are getting duplicated. So the solution which I think feasible is disable Sidekiq::Cron::Poller or Sidekiq::Cron for all servers except one so that only one server will be responsible for scheduling and polling. So Is there anyway in Sidekiq::Cron ?

**Comment by mohsintahir** [comment]
Closed this because I disabled sidekiq-cron in the sidekiq processes where i don't want to run it by overriding Sidekiq::Cron::Poller classes in `Sidekiq.configure_server{ |config| config.on(:startup)}` e.g.

```
Sidekiq.configure_server do |config|
   config.on(:startup) do
       if config.options[:disable_cron] # disable_cron is a variable i set in sidekiq.yml file
          Sidekiq::Cron::Poller.class_eval{
              def start; end
              def terminate; end
          }
       end 
   end
end
```

**Comment by bdegomme** [comment]
I had a similar issue: I wanted to disable sidekiq cron jobs in my development environment, to avoid crowding out my logs.
I added the following in sidekiq.rb
```
if Rails.env.development? || Rails.env.testing?
  Sidekiq::Cron::Job.class_eval do
    def save; end
  end
end
```

**Comment by olivier-thatch** [comment]
I found this topic via Google, so posting my solution here in case it's helpful to anyone else. I added the following to the `config/initializers/sidekiq.rb` initializer file:

```ruby
Sidekiq.configure_server do |config|
  # existing server config here

  # Disable all cron jobs in development and testing.
  # Jobs can still be enqueued or re-enabled manually from the Sidekiq UI.
  if Rails.env.development? || Rails.env.test?
    config.on(:startup) do
      Sidekiq::Cron::Job.all.each(&:disable!) # rubocop:disable Rails/FindEach
      Sidekiq.logger.info { "Cron Jobs - disabled all jobs" }
    end
  end
end
```

I think this is less hacky than monkey-patching `Sidekid::Cron::Job`. It simply disables all jobs during local development, but they can still be manually enqueued or enabled from the Sidekiq UI.

**Comment by axos88** [comment]
Note that the solution by @olivier-thatch will not disable any jobs created during load (such as after a redis flushall), only after the second restart
