### ISSUE TITLE
Upgrade to sidekiq 6.0.1 (Sidekiq pro 5.0.1) breaks sidekiq-cron

### ISSUE THREAD

**Issue by amitsaxena** [ondrejbartas/sidekiq-cron#259]
We upgraded from sidekiq-pro 5.0.0 to 5.0.1 (which in turn upgraded sidekiq dependency 6.0.0 --> 6.0.1) yesterday and it seems to have resulted in a broken cron setup for us on production. We noticed that the "Last enqueued" timestamp in dashboard was getting updated, but the actual jobs weren't getting executed.

We had to rollback to `6.0.0` to get it working again. We are using `sidekiq-cron` version `1.1.0`.

**Comment by yxhuvud** [comment]
https://github.com/mhenrixon/sidekiq-unique-jobs/issues/427 could perhaps be related.

**Comment by amitsaxena** [comment]
Also I added an issue here already: https://github.com/ondrejbartas/sidekiq-cron/issues/259

Upvotes might be helpful.

**Comment by CHTJonas** [comment]
This seems to be working now I think? Tested with:

```
rails 6.0.2.1
sidekiq 6.0.4
sidekiq-cron 1.1.0
```

**Comment by amitsaxena** [comment]
This no longer seems to be an issue for us on `sidekiq-6.0.3`.
