### ISSUE TITLE
Support Dark Mode (Sidekiq v6.0.1)

### ISSUE THREAD

**Issue by CHTJonas** [ondrejbartas/sidekiq-cron#260]
The latest release of Sidekiq now detects if the user's browser is reporting that it is in 'dark mode' and changes the theme accordingly. However, `sidekiq-cron`'s buttons don't play nicely with this:

<img width="426" alt="Screenshot 2019-10-09 at 23 14 24" src="https://user-images.githubusercontent.com/17813061/66524519-92580680-eaea-11e9-8333-93fc4c8a9a14.png">

**Comment by kaka-ruto** [comment]
<img width="1435" alt="Screenshot 2021-03-23 at 23 20 38" src="https://user-images.githubusercontent.com/16320124/112212929-9cae8780-8c2e-11eb-8471-7544e6bbe33d.png">
