### ISSUE TITLE
Cron jobs do not automatically inherit from ActiveJob queue_as field

### ISSUE THREAD

**Issue by hectorakemp** [ondrejbartas/sidekiq-cron#269]
Hi there, 

Thanks again for this immensely useful gem. 

I have a small issue with which queues jobs are sent to in schedule.yml. 

Given a job spec defined in `schedule.yml` as such:

```
ExampleJob
  cron: '* * * * *'
  class: 'ExampleJob'
```

Which has an ActiveJob `queue_as :my_queue` in its job spec, the scheduler ignores the queue field from the ActiveJob spec, and uses `queue: default` instead. This means we have to define our jobs as such:

```
ExampleJob
  cron: '* * * * *'
  class: 'ExampleJob'
  queue: 'my_queue'
```

which leads to a bit of duplication, as it's defined in both the ActiveJob spec and `schedule.yml`. Is it possible to make it so that if the `queue` field is not defined for a job in `schedule.yml`, it automatically inherits it from ActiveJob?

Thanks again, 

Hector

**Comment by adamzapasnik** [comment]
could we get this re-opened and fixed?

**Comment by markets** [comment]
Please, feel free to send a patch! We'd be happy to review it!
