### ISSUE TITLE
High CPU usage when having a lot of crons

### ISSUE THREAD

**Issue by adank92** [ondrejbartas/sidekiq-cron#276]
Recently I found myself debugging a weird issue where our Sidekiq servers were using 100% CPU pretty much all the time. After some time profiling a Sidekiq process I was able to see that the problem was related to `sidekiq-cron`. Let me explain.

Our project has a lot of crons, nearly a thousand of them. `sidekiq-cron` uses the following gems to calculate if a cron needs to be run or not every 30 seconds: 
sidekiq-cron > [fugit](https://github.com/floraison/fugit) > [et-orbi](https://github.com/floraison/et-orbi) > [chronic](https://github.com/mojombo/chronic) (optional)

Chronic is a natural language date/time parser written in pure Ruby, it does a really good job but it is very slow and CPU expensive to use at a large scale. This is an example of what `sidekiq-cron` does internally:
```
> crons = ["0 8 1 * * America/Chicago"] * 1000
> time = Time.now
> puts Benchmark.measure { crons.map { |cron| Fugit.parse_cron(cron).previous_time(time).utc } }.to_s
110.393223   0.960230 111.353453 (111.392823)
```

`et-orbi` uses `chronic` by default but it not necessary for `sidekiq-cron` since it always uses the same format. Luckily, `et-orbi` provides a way disable it and doesn't change the behavior what so ever:
```
> crons = ["0 8 1 * * America/Chicago"] * 1000
> time = Time.now
> EtOrbi.chronic_enabled = false
> puts Benchmark.measure { crons.map { |cron| Fugit.parse_cron(cron).previous_time(time).utc } }.to_s
25.526977   0.459915  25.986892 ( 25.988946)
```

Disabling chronic and changing `Sidekiq.options[:poll_interval] = 60.seconds` made a huge improvement in our application. 

I think this is something that could be improved in this gem but will possibly require changes in those other gems as well, as disabling `et-orbi`'s chronic use globally can harm some applications that do need it.

**Comment by jmettraux** [comment]
Hello and thanks for reporting that.

Et-orbi was calling Chronic unnecessarily. This has been [fixed](https://github.com/floraison/et-orbi/issues/28) and [et-orbi 1.2.4](https://rubygems.org/gems/et-orbi/versions/1.2.4) has been pushed to RubyGems.org.

Best regards.
