### ISSUE TITLE
Cron jobs not loading

### ISSUE THREAD

**Issue by zorar4ik** [ondrejbartas/sidekiq-cron#283]
Hi, I have added sidekiq and sidekiq-cron to my project but It seems like cron jobs are not loading from my yml file. Here is my config:

Gemfile:
```
sidekiq (6.0.6)
sidekiq-cron (1.2.0)
```

My sidekiq.rb:
```
# frozen_string_literal: true

if ENV['SKIP_SIDEKIQ'].blank?
  schedule_file = 'config/schedule.yml'
  schedule = {}

  schedule = ::YAML.load_file(schedule_file) if ::File.exist?(schedule_file) && ::Sidekiq.server?

  ::Sidekiq::Cron::Job.load_from_hash(schedule)
end
```

Variable `SKIP_SIDEKIQ` equals `nil`:
```
ENV['SKIP_SIDEKIQ'].blank?
=> true
```

My scheduler looks like this:
```
send_invoice:
  cron: "0 0 1 1 *"
  class: "CompanyInvoiceWorker"
  queue: mailers
```

`Sidekiq.yml` just in case: 
```
---
:verbose: false
:concurrency: 5
:timeout: 30
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - default
  - mailers
production:
  :concurrency: 10
```

I have no idea what is wrong, cron page on UI says only `No cron jobs were found`

**Comment by ondrejbartas** [comment]
@zorar4ik Hi you need to start sidekiq ctl to process jobs, than your sidekiq.rb code needs to run
check if `::File.exist?(schedule_file) && ::Sidekiq.server?` these conditions are matched

Also you can run ruby console (pry, irb, rails c) and try to run `::Sidekiq::Cron::Job.load_from_hash(schedule)` what will happen?

**Comment by zorar4ik** [comment]
@ondrejbartas hi, thanks for reply. I don't remember what I have done, most probably there were issues with my nginx configurations, if this is possible. So I am closing this issue as it is not relevant. Thanks for gem!
