### ISSUE TITLE
Redis#exists(key) Warning from redis 4.2.0

### ISSUE THREAD

**Issue by majksner** [ondrejbartas/sidekiq-cron#286]
mperham/sidekiq#4591

Changes needed:

https://github.com/ondrejbartas/sidekiq-cron/blob/master/lib/sidekiq/cron/job.rb#L464
```diff
- conn.zadd(job_enqueued_key, time.to_f.to_s, formated_last_time(time).to_s) unless conn.exists(job_enqueued_key)
+ conn.zadd(job_enqueued_key, time.to_f.to_s, formated_last_time(time).to_s) unless conn.exists?(job_enqueued_key)
```
https://github.com/ondrejbartas/sidekiq-cron/blob/master/lib/sidekiq/cron/job.rb#L543
```diff
- out = conn.exists redis_key name
+ out = conn.exists? redis_key name
```

**Comment by jankeesvw** [comment]
I'm also seeing this deprecation warning, can I do anything to fix this?

**Comment by majksner** [comment]
@jankeesvw Until it's fixed you can fork library and change what I have above and point your Gemfile to your github repository.

**Comment by MikeRogers0** [comment]
@jankeesvw 

Update your Gemfile to track my bugfix branch:

```ruby
gem 'sidekiq-cron', github: 'MikeRogers0/sidekiq-cron', branch: 'bug/fix-redis-warning'
```

:)

**Comment by cbaudouinjr** [comment]
Any updates on getting this PR to pass CI/get merged in? I can help if needed!

**Comment by botularius** [comment]
Any news on this?

**Comment by hebbo** [comment]
Keeping an eye here also in search of a fix. Thanks!

**Comment by MikeRogers0** [comment]
I sent an email to @ondrejbartas to see if he's ok & will merge my PR with the fix to this.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ping @ondrejbartas

**Comment by olegykz** [comment]
@tleish I've created https://github.com/ondrejbartas/sidekiq-cron/pull/318 to finally get rid of the deprecation warning
