### ISSUE TITLE
NotImplementedError: NotImplementedError when using sidekiq_options retry: false with ActiveJob

### ISSUE THREAD

**Issue by fabioxgn** [ondrejbartas/sidekiq-cron#291]
As I've explained in the Sidekiq issue https://github.com/mperham/sidekiq/issues/4665 when using `sidekiq_options retry: false` and `config.cache_classes = true` the `sidekiq-cron` is probrably constantizing the job class on initialization which causes `NotImplementedError: NotImplementedError` in runtime.

To reproduce this problem I just need to add `sidekiq_options retry: false` in any ActiveJob class, set  `config.cache_classes = true` and load the job schedule from yml.

If I remove this line from my initialization everything works, so it's not a Sidekiq issue.
```ruby
Sidekiq::Cron::Job.load_from_hash YAML.load_file("config/schedule.yml")`.
```

Maybe this is caused by the gem constantizing the class to read the `sidekiq_options` to get the queue info? https://github.com/ondrejbartas/sidekiq-cron/blob/master/lib/sidekiq/cron/job.rb#L306

**Comment by fabioxgn** [comment]
I was able to nail down the problem to this line: https://github.com/ondrejbartas/sidekiq-cron/blob/master/lib/sidekiq/cron/job.rb#L306

This is raising an error that is being ignored:
```ruby
NoMethodError: undefined method `sidekiq_options' for MySchedulerJob:Class
```

But after this error the JobClass stays invalid, I guess because it was not loaded properly.

**Comment by jankeesvw** [comment]
I just ran into exactly the same issue. Can I help in getting this fixed?

**Comment by jeanmartin** [comment]
Me too. Thank your for all the digging! I guess I will try out https://github.com/moove-it/sidekiq-scheduler instead then.

**Comment by fabioxgn** [comment]
> Me too. Thank your for all the digging! I guess I will try out https://github.com/moove-it/sidekiq-scheduler instead then.

@jeanmartin I've migrated my projects to sidekiq-scheduler because of this bug and it's working great.

**Comment by kevinjalbert** [comment]
Just to mention, I have the exact same error and it appears when using `sidekiq_options retry: 3`.

**Comment by CarlosCD** [comment]
Same problem here with `sidekiq_options retry: false`. So it seems to be <https://github.com/ondrejbartas/sidekiq-cron/blob/master/lib/sidekiq/cron/job.rb#L306>, as @fabioxgn mentioned.

The problem goes away by removing the `sidekiq_options` method call.

**Comment by shqear93** [comment]
Is anybody able to fix this?

**Comment by shqear93** [comment]
anybody here?

**Comment by newtonjose** [comment]
Hi, I try solve using `retry_on CustomAppException # defaults to 3s wait, 5 attempts` from rails docs [Retrying or Discarding failed jobs](https://edgeguides.rubyonrails.org/active_job_basics.html#retrying-or-discarding-failed-jobs).

**Comment by ondrejbartas** [comment]
Nice finding in sidekiq-scheulder. Sam princip will work for sidekiq-cron too.

so fix for this is move  load of sidekiq config to 
```
if ENV['REDIS_URL']
  Sidekiq.configure_client do |config|
    config.redis = { url: ENV['REDIS_URL'], network_timeout: 5 }
  end
  
  Sidekiq.configure_server do |config|
    config.redis = { url: ENV['REDIS_URL'], network_timeout: 5 }
+   config.on(:startup) do
      # Grab your scheduling yaml file to load into corn
      schedule_file = "config/schedule.yml"
      if File.exists?(schedule_file)
        Sidekiq.schedule = YAML.load_file(schedule_file)
        SidekiqScheduler::Scheduler.instance.reload_schedule!
      end
+    end
  end
end
```
