### ISSUE TITLE
Add description field to schedule configuration

### ISSUE THREAD

**Issue by rhymes** [ondrejbartas/sidekiq-cron#294]
Would it make sense to add a description field to `config/schedule.yml` ?

Cron syntax is always one of those things that no matter how many years I have been developing I ultimately have to figure out each time. 

It would be awesome to have a description field, both in the YAML file and in the UI so a person can write stuff like `Runs on tuesday, each 15m minutes` or something like that :D 

I can contribute a patch if approved

**Comment by dmitry** [comment]
Would be great to have an alternative "human time" for each scheduled job using https://github.com/alpinweis/cronex.

**Comment by FabricioFFC** [comment]
@rhymes I tried to put a description in my `schedule.yml` and it worked.

But it shows only in the cron job details in sidekiq web:

![Screenshot from 2021-01-19 16-43-44](https://user-images.githubusercontent.com/139354/105084772-9a388180-5a75-11eb-9d99-33476d6fbb3b.png)

**Comment by rhymes** [comment]
Thanks @FabricioFFC, I tried the same and it worked. I'm closing this issue then.
