### ISSUE TITLE
Incorrect Last Enqueued Date

### ISSUE THREAD

**Issue by kylekeesling** [ondrejbartas/sidekiq-cron#30]
It seems as though the last enqueued dates are not reflecting the actual last time the job was ran, but rather the time since midnight. Even if I manually enqueue a job the date does not update. Any ideas as to what I could be doing wrong?

**Comment by ondrejbartas** [comment]
The problem is that last enqued time is used internaly for sidekiq-cron to decide if it needs to be added or not.
