### ISSUE TITLE
NoMethodError: undefined method `jid=' for

### ISSUE THREAD

**Issue by vitobotta** [ondrejbartas/sidekiq-cron#300]
Hi!

Thanks for this gem, very useful. I have been using it for a while and the only issue that I have is that quite often jobs enqueued fail with the error in the subject, but only in development. It doesn't seem to happen in production.

I am currently using Sidekiq 6.1.2. Is sidekiq-cron fully compatible with this version?

Thanks!

**Comment by iHiD** [comment]
I'm also getting this. I've tried upgrading to the `6.2.1` and still get the same. @vitobotta Did you solve this?

**Comment by vitobotta** [comment]
@iHiD Nope, still happening...

**Comment by christopheragnus** [comment]
anyone able to solve this? are you guys using Activejob or Sidekiq Workers?

looks like there's a similar problem: https://github.com/mperham/sidekiq/issues/3593

**Comment by iHiD** [comment]
No. I switched to `sidekiq-scheduler` instead. I couldn't make it stop with `sidekiq-cron`.

**Comment by phlegx** [comment]
See https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs#notes
Cron jobs must use `Sidekiq::Job`, not `ActiveJob`.
