### ISSUE TITLE
Redis#exists boolean behaviour will be deprecated in redis-rb 4.3

### ISSUE THREAD

**Issue by vknightbd** [ondrejbartas/sidekiq-cron#304]
I get the following on my server log with redis 4.2.5 and navigating to http://localhost:3000/admin/sidekiq/cron and clicking Enqueue on a job. 

``
`Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0. (/Users/jameslam/.rvm/gems/ruby-2.7.3/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:543:in `block in exists?')
``

**Comment by kanroyalhigh** [comment]
was about to add an issue like this and initiate a PR. fortunately PR #288 that will address this issue was already done and merged. :)

**Comment by leecunliffe** [comment]
Would be nice to have a release that included this change?

**Comment by chienkira** [comment]
Hi. Still not releases yet?

**Comment by ftopan80** [comment]
I also would like to have this fix in a new release please...

**Comment by gilest** [comment]
@ondrejbartas @MikeRogers0 any chance of cutting a release? 🙇

**Comment by bruno-** [comment]
Hi guys, here's another gentle reminder to please cut a new release when you get a chance. Thanks!

**Comment by ondrejbartas** [comment]
Hi released in 1.3.0
