### ISSUE TITLE
[UI] "Show ALL" button on Cron Jobs is not working on Sidekiq v6.3.0+

### ISSUE THREAD

**Issue by fukayatsu** [ondrejbartas/sidekiq-cron#308]
<img width="717" alt="ss 2021-11-22 10 59 27" src="https://user-images.githubusercontent.com/1041857/142790221-8e53972d-1d67-4a41-9191-9fa92acbfa33.png">

> `Uncaught TypeError: Cannot read properties of null (reading 'style')`

This is because jQuery has been removed on Sidekiq v6.3.0.

Maybe this change on sidekiq would help: 
https://github.com/mperham/sidekiq/pull/5036/files#diff-3ea6493e3b9dd0a7071089f2ce1d60a8504cc9f1d3790b0fb54807fdcc08fa75L37-R39

**Comment by ondrejbartas** [comment]
Hi @fukayatsu 
I would like to mainintain compatibility with older sidekiq versions so this could be somehow problematical. 

only solution which is ok from my perspective is to add condition which will render code for new sidekiq version and for old version it will render same code as it is now in templates.

What do you think?

**Comment by fukayatsu** [comment]
@ondrejbartas 

> only solution which is ok from my perspective is to add condition which will render code for new sidekiq version and for old version it will render same code as it is now in templates.

I would prefer that approach as well 😄

**Comment by ondrejbartas** [comment]
@fukayatsu cool will you create PR for this change?

**Comment by fukayatsu** [comment]
@ondrejbartas I made a PR #321 for this issue. Can you please review it?
