### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by mathieujobin** [ondrejbartas/sidekiq-cron#315]
@ondrejbartas are you still able to make releases for this gem?

Anyone else interested taking over?

I am not super interested migrating to https://github.com/moove-it/sidekiq-scheduler

but if no one steps up to make a new release, we'll have to

**Comment by boushley** [comment]
We're planning to migrate to: https://github.com/Moove-it/sidekiq-scheduler which appears to have similar functionality and still be maintained.

**Comment by chloerei** [comment]
sidekiq-scheduler will enqueue duplicate jobs in multiple processes, sidekiq-cron will ensure that there is only one.

I hope sidekiq-cron will continue to be maintained.

**Comment by AxelTheGerman** [comment]
@chloerei can you provide some more details on this:

> sidekiq-scheduler will enqueue duplicate jobs in multiple processes, sidekiq-cron will ensure that there is only one.

Is this more of an edge case or is it some kind of de-dup feature that `sidekiq-cron` has?

**Comment by chloerei** [comment]
@AxelTheGerman I don't actually use sidekiq-scheduler, but according to the documentation:

https://github.com/moove-it/sidekiq-scheduler#notes-about-running-on-multiple-hosts

> ## Notes about running on Multiple Hosts
> Under normal conditions, cron and at jobs are pushed once regardless of the number of sidekiq-scheduler running instances, assumming that time deltas between hosts is less than 24 hours.
>
> Non-normal conditions that could push a specific job multiple times are:
>
> - high cpu load + a high number of jobs scheduled at the same time, like 100 jobs
> - network / redis latency + 28 (see MAX_WORK_THREADS https://github.com/jmettraux/rufus- scheduler/blob/master/lib/rufus/scheduler.rb#L41) or more jobs scheduled within the same network latency window
> 
> every, interval and in jobs will be pushed once per host.

And there are issues:

https://github.com/moove-it/sidekiq-scheduler/issues/332
https://github.com/moove-it/sidekiq-scheduler/issues/181

On the other side, sidekiq-cron's document:

> Scheduling jobs are added only when at least one Sidekiq process is running, but it is safe to use Sidekiq-Cron in environments where multiple Sidekiq processes or nodes are running.

> ## Under the hood
> Sidekiq-Cron is safe to use with multiple sidekiq processes or nodes. It uses a Redis sorted set to determine that only the first process who asks can enqueue scheduled jobs into the queue.

**Comment by ondrejbartas** [comment]
Hi sorry for not responding sooner. 

Currently I am occupied at my daily job.

I will revisit all pending PRs and try to merge them and release them in 2 weeks.

is this ok for you guys?

**Comment by markets** [comment]
Thanks for your response and the merges you just did @ondrejbartas!

No prob, this is open-source after all! But considering this gem is very used (more then 28M downloads according RubyGems) by the community, I think it would be nice to:

- add new maintainers to this repo
- move the project to a new org in GitHub and add more maintainers too

It seems there are some people willing to help, like:

- @honzasterba: https://github.com/ondrejbartas/sidekiq-cron/pull/297#issuecomment-897054911
- @MikeRogers0: https://github.com/ondrejbartas/sidekiq-cron/pull/297#issuecomment-897062443

And myself (and my team at Crisalix) would also be able to help, at least, reviewing PRs, closing obsolete issues, testing new RCs, ...

We also considered moving to `moove-it/sidekiq-scheduler`, but this https://github.com/moove-it/sidekiq-scheduler#notes-about-running-on-multiple-hosts is not a viable option for us 😄

**Comment by ondrejbartas** [comment]
Thanks @markets  I just made you colaborator of this repo, same with @honzasterba and @MikeRogers0 

I also created slack workspace and send you invite. So hopeflly there will be no problem maintaining this repo in future.

I will release new version 1.3.0 now

**Comment by ondrejbartas** [comment]
BTW if anyone is interested in helping this is a link to slack channel (valid for 30 days) https://join.slack.com/t/sidekiq-cron/shared_invite/zt-16t5f0ixu-9RTBJQCWPcJwePkPm3q_LA so join us
