### ISSUE TITLE
Redis.rb deprecation warning with exists_returns_integer=false

### ISSUE THREAD

**Issue by v-kumar** [ondrejbartas/sidekiq-cron#320]
With the version 1.3.0, we get this new deprecation warning now.

This should not be raised if redis-rb gem > v 4.3. Redis has added exists? method for a long time now.

`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
/usr/local/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-cron-1.3.0/lib/sidekiq/cron.rb:7:in `<module:Cron>'
/

**Comment by markets** [comment]
Hi @v-kumar

That's already fixed on master: https://github.com/ondrejbartas/sidekiq-cron/pull/318

**Comment by v-kumar** [comment]
Thank you. Can you cut a new release with #318 ?

**Comment by markets** [comment]
We'll do soon! In the meantime, you can point the gem to GitHub `master` branch: 

```ruby
gem 'sidekiq-cron', github: 'ondrejbartas/sidekiq-cron'
```

Sorry for any inconvenience!

**Comment by Laykou** [comment]
When is "soon"? :)

**Comment by markets** [comment]
I'll try to prepare this release tonight :bowtie:

**Comment by markets** [comment]
Live 🚀  https://rubygems.org/gems/sidekiq-cron/versions/1.4.0
