### ISSUE TITLE
Usage of same setting average_scheduled_poll_interval

### ISSUE THREAD

**Issue by phyzalis** [ondrejbartas/sidekiq-cron#323]
Hi,

We have recently updated to version `1.3.0` and we have a large increase in the CPU usage on our production platform.
We have sidekiq setting `average_scheduled_poll_interval` set to 5 seconds because we want to be able to delay a job with this granularity.

But it seems that Sidekiq-cron is using exactly the same setting to know how often it should check for cron jobs to execute and we do have a lot of cron jobs.

As cron-job are per minutes, why do Sidekiq-cron uses the same setting ? Why not having define another setting ?

Waiting for the answer I will change our setting to 20s but could you explain the reason ?

Thank you

**Comment by markets** [comment]
The current `Poller` class inherits from the Sidekiq class:

https://github.com/ondrejbartas/sidekiq-cron/blob/30d712ac9c943fa3164c880957fd978fbc4b0f19/lib/sidekiq/cron/poller.rb#L11
https://github.com/ondrejbartas/sidekiq-cron/blob/30d712ac9c943fa3164c880957fd978fbc4b0f19/lib/sidekiq/cron/poller.rb#L37

So I think it makes sense to inherit the same Sidekiq setting by default, but it also seems reasonable to introduce a _new_ custom option in this direction:

```ruby
def poll_interval_average
  _this_new_option_ || Sidekiq.options[:average_scheduled_poll_interval] || POLL_INTERVAL
end
```

**Comment by phyzalis** [comment]
Thanks for your point

I was having the same idea of adding an extra optional setting to allow to override this.
