### ISSUE TITLE
High CPU usage with lots of tasks

### ISSUE THREAD

**Issue by phyzalis** [ondrejbartas/sidekiq-cron#327]
Hi,

I've readen this issue that has been closed : https://github.com/ondrejbartas/sidekiq-cron/issues/276 but with near 3500 tasks in our system we are facing too much usage of CPU.

For sure the `previous_time` function is a CPU killer. Are we the only team to face that ?
Is there any solution to prevent this ? (we are using a fork of the last version of the gem)

**Comment by jmettraux** [comment]
`Fugit::Cron#previous_time` is used in two places:

* https://github.com/ondrejbartas/sidekiq-cron/blob/c91d0f22f95cb3a297c06e2c15494d95c8085f28/lib/sidekiq/cron/job.rb#L534
* https://github.com/ondrejbartas/sidekiq-cron/blob/c91d0f22f95cb3a297c06e2c15494d95c8085f28/lib/sidekiq/cron/job.rb#L620

I suggest not using it.

I suggest doing like In [rufus-scheduler](https://github.com/jmettraux/rufus-scheduler), each time a job triggers, its equivalent `#last_cron_time` is set at the current trigger time, and `#previous_time` is not used.

I think it's an easy way to avoid the cost of calling `#previous_time` for a piece of information whose intent (`#last_cron_time`) is more about "last time it triggered" than "previous time it should have triggered".

**Comment by phyzalis** [comment]
Thank you for your really fast answer

Could you develop what we can do like rufus-scheduler ? I am not used to rufus-scheduler (yet)

**Comment by jmettraux** [comment]
@phyzalis sorry, my answer was directed at the maintainers of sidekiq-cron. If you use sidekiq-cron, then you don't need rufus-scheduler.

Roughly, since Sidekiq-Cron can store info in Redis (like it seems to do for `last_enqueue_time`), it should avoid calling `Fugit::Cron#next_time` or `Fugit::Cron#previous_time` more than once. It should compute it and store it, hopefully, as Sidekiq keeps the job at hand, it shouldn't need to read it (from Redis) or compute it.

**Comment by phyzalis** [comment]
@jmettraux thank you for your explanation, I am understanding now

Yes your solution seems better as we will compute `next_time` only one time per execution of a task, instead of calling `previous_time` on each task on a polling basis

**Comment by jmettraux** [comment]
Maybe this cheap change could help:
```diff
diff --git a/lib/sidekiq/cron/job.rb b/lib/sidekiq/cron/job.rb
index e2d2144..de0be21 100644
--- a/lib/sidekiq/cron/job.rb
+++ b/lib/sidekiq/cron/job.rb
@@ -74,6 +74,8 @@ module Sidekiq
             end
           end
 
+        @last_cron_time = nil
+
         save_last_enqueue_time
         add_jid_history jid
         logger.debug { "enqueued #{@name}: #{@message}" }
@@ -617,10 +619,10 @@ module Sidekiq
       end
 
       def not_past_scheduled_time?(current_time)
-        last_cron_time = parsed_cron.previous_time(current_time).utc
+        @last_cron_time ||= parsed_cron.previous_time(current_time).utc
           # or could it be?
-        #last_cron_time = last_time(current_time)
-        return false if (current_time.to_i - last_cron_time.to_i) > 60
+        #@last_cron_time ||= last_time(current_time)
+        return false if (current_time.to_i - @last_cron_time.to_i) > 60
         true
       end
```

**Comment by phyzalis** [comment]
in fact as the second call to `last_time` is commented, I don't see the point in using this `@last_cron_time`

`not_past_scheduled_time?` is only called once, isn't it ?

**Comment by jmettraux** [comment]
> in fact as the second call to `last_time` is commented, I don't see the point in using this `@last_cron_time`
>
> `not_past_scheduled_time?` is only called once, isn't it ?

OK. Then let's roll back to your initial claim.

> For sure the `previous_time` function is a CPU killer.

Yes, it may be costly. It seems you did some analysis to come to that conclusion. At what point in Sidekiq-Cron do you see `previous_time` getting called? Please share your information.

**Comment by phyzalis** [comment]
`previous_time` is called in `not_past_scheduled_time?` on jobs to see if they should enqueue with `should_enque?`

this is used in `Poller` on each Job to check if it should enqueue.

Based on `poll_interval_average`, the poller is executed and each Job are tried

On my side, my test was quite simple. I've prepared a cron list same amount of jobs as I have in my system and here are the results :


```
irb(main):001:0> crons = nil
=> nil
irb(main):002:0>
irb(main):003:0> puts Benchmark.measure {
irb(main):004:1*   crons = ([ '0 8 1 * *' ] * 3232)
irb(main):005:1>     .collect { |c| Fugit.parse(c) }
irb(main):006:1> }
  2.447388   0.046236   2.493624 (  2.506266)
=> nil
irb(main):007:0>
irb(main):008:0> time = Time.now
=> 2022-04-15 14:48:26 +0200
irb(main):011:0>
irb(main):012:0> puts Benchmark.measure {
irb(main):013:1*   crons.map { |cron| cron.previous_time(time) }
irb(main):014:1> }.to_s
102.807576   0.648054 103.455630 (105.881329)
=> nil
```

If every 30s, I have a task that needs 100s to complete, there is an issue.
It seems that the complexity of the cron have an impact (`* * * * *` is really faster than `0 8 1 * *`) but my point is here

I was wondering if something else than `previous_time` could be used, and you came with a solution with using the `next_time` with seems to be a great improvement. I am not sure to be able to do this kind of changes on the gem but we will look on our side.
Or maybe in our application, we will create a task per minute (so 1440 tasks) and stores what we want to execute on each of these minutes.

**Comment by jmettraux** [comment]
```ruby
require 'benchmark'
require 'fugit'

puts RUBY_VERSION

cs = ([ '0 8 1 * *' ] * 3232).collect { |c| Fugit.parse(c) }
t = Time.now

puts Benchmark.measure {
  cs.each { |c| c.previous_time(t) } }
puts Benchmark.measure {
  cs.each { |c| c.next_time(t) } }
```

```
2.7.1
87.160000   0.070000  87.230000 ( 91.731789)
22.570000   0.030000  22.600000 ( 23.991014)
```

**Comment by phyzalis** [comment]
Better performance and the point is that `next_time` in your suggestion won't be called for each job in a loop every 30s but only once per job execution
