### ISSUE TITLE
Deprecated warning at add_jid_history

### ISSUE THREAD

**Issue by byungjikroh** [ondrejbartas/sidekiq-cron#339]
Hello

After upgrading Sidekiq and Sidekiq-cron versions, I've got this deprecated warning at add_jid_history.

Since I don't use Rails and can't find how to fix this warning. 

Thanks

Sidekiq v6.5.1
Sidekiq-cron v1.5.1

```
`config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/app/vendor/bundle/ruby/2.6.0/gems/sidekiq-cron-1.5.1/lib/sidekiq/cron/job.rb:481:in `add_jid_history'", "/app/vendor/bundle/ruby/2.6.0/gems/sidekiq-cron-1.5.1/lib/sidekiq/cron/job.rb:73:in `enque!'"]
```

**Comment by markets** [comment]
See more info in: https://github.com/ondrejbartas/sidekiq-cron/pull/338
