### ISSUE TITLE
New Feature: backfills

### ISSUE THREAD

**Issue by antulik** [ondrejbartas/sidekiq-cron#34]
Would be nice to have backfill option, to enqueue the job if it has been skipped last time for some reason

this is exactly the same functionality as in sidetiq gem https://github.com/tobiassvn/sidetiq/wiki/Backfills

**Comment by pchaganti** [comment]
+ 1

**Comment by gfoiani** [comment]
+1

**Comment by ivanovv** [comment]
+1

**Comment by ondrejbartas** [comment]
Still needed?

**Comment by zedtux** [comment]
Yep @ondrejbartas please :)

**Comment by antulik** [comment]
yes, would be good to have it
