### ISSUE TITLE
[UI] Disabled CronJob in dark is difficult to read

### ISSUE THREAD

**Issue by djpremier** [ondrejbartas/sidekiq-cron#347]
The job title (which is also a link), disabled in dark mode, is gray, but without any contrast with the red background, making it extremely difficult to read.

![image](https://user-images.githubusercontent.com/17091381/178367881-f091d907-cbfb-4c94-ba3a-87d7b0e93776.png)

**Comment by markets** [comment]
Thanks for reporting @djpremier! I agree this is now difficult to read (dark theme + disable job), feel free to send a patch.

**Comment by markets** [comment]
Fixed by #351
