### ISSUE TITLE
Cron does not gets deleted on destroy

### ISSUE THREAD

**Issue by surbhig213** [ondrejbartas/sidekiq-cron#352]
We are calling cron.destroy after the cron job execution. The cron is not getting deleted on calling this destroy method. 
The keys for this cron are still present in the Redis. And the cron gets updated with the name as nil

This is how the cron looks if we try to find it after the destroy method is called

Sidekiq::Cron::Job.find("test-cron-name")
=> {
                    :name => nil,
                   :klass => nil,
                    :cron => nil,
             :description => nil,
                    :args => "[]",
                 :message => "{}",
                  :status => "enabled",
              :active_job => false,
       :queue_name_prefix => nil,
    :queue_name_delimiter => nil,
       :last_enqueue_time => 2022-08-02 16:54:17 UTC
}

Can you please help with this?

**Comment by markets** [comment]
I'm trying to reproduce it, but it seems to work fine... Just tested on my app, via console:

```ruby
>> Sidekiq::Cron::Job.all.size
=> 3
>> job = Sidekiq::Cron::Job.find('fetch_cases')
=> #<Sidekiq::Cron::Job:0x00007fcc3041ee80 @fetch_missing_args=true, @name="fetch_cases", @cron="every 12 hours", @klass="FetchCasesJob", @status="enabled", @last_enqueue_time=nil, @sym...
>> job.destroy
2022-08-19T20:00:09.626Z pid=83979 tid=1sqr INFO: Cron Jobs - deleted job with name: fetch_cases
=> 97
>> Sidekiq::Cron::Job.find('fetch_cases')
=> nil
>> Sidekiq::Cron::Job.all.size
=> 2
```

We also have some ✅ tests: https://github.com/ondrejbartas/sidekiq-cron/blob/313bf3463dff254b44c787b79504db53dbb4fe88/test/unit/job_test.rb#L952.

Please, provide a reproducible demo or a failing test case, so we can take a deeper look.
