### ISSUE TITLE
Sidekiq cron affects Sidekiq scheduled set polling interval

### ISSUE THREAD

**Issue by engwan** [ondrejbartas/sidekiq-cron#358]
This is a bug introduced in https://github.com/ondrejbartas/sidekiq-cron/pull/331/files (v1.5.0).

Previously, we were overriding the `poll_interval_average` method in the poller class. This means it only affects `Sidekiq::Cron::Poller` which is what we want.

With that PR, we are now setting the `poll_interval_average` Sidekiq option, which means Sidekiq would be using this interval instead of the scaled interval based on number of Sidekiq processes: https://github.com/mperham/sidekiq/blob/f3e0640a79fec2ea9a87bdfab12e7c45b4153778/lib/sidekiq/scheduled.rb#L176-L178

**Comment by markets** [comment]
> Previously, we were overriding the poll_interval_average method in the poller class. This means it only affects Sidekiq::Cron::Poller which is what we want.

That's right!

@danilogco what do you think? Can we restore somehow that behavior?
