### ISSUE TITLE
Default polling interval is 5 seconds and not 30 seconds as documented

### ISSUE THREAD

**Issue by engwan** [ondrejbartas/sidekiq-cron#361]
From https://github.com/ondrejbartas/sidekiq-cron/pull/359#discussion_r965969273:

> I do not agree with using average_scheduled_poll_interval here because this makes it intertwined with the Sidekiq setting.
> 
> Default value for this in Sidekiq is actually 5 seconds. So when we introduced this option, we actually dropped the default interval to 5 seconds and the docs are wrong.
> 
> I think a better approach would be to use a different setting like cron_poll_interval. I kept this as-is in this PR though since this is a different bug.

**Comment by markets** [comment]
hey @engwan now that #359 has been merged, are you interested in working on this?
