### ISSUE TITLE
Use Redis#sadd? instead of Redis#sadd

### ISSUE THREAD

**Issue by f-ewald** [ondrejbartas/sidekiq-cron#363]
I see the following message popping up in the logs:

> Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /usr/local/lib/ruby/gems/3.1.0/gems/sidekiq-cron-1.7.0/lib/sidekiq/cron/job.rb:468:in `block in save')

It seems to me that this is save to change.

**Comment by markets** [comment]
Hello @f-ewald 

I think we can close this one, as we already pushed this to `master`: https://github.com/ondrejbartas/sidekiq-cron/commit/1f9cc7ddf386de0d35d41afd5995d9a99e18d4e7. It will be included in the next release.
