### ISSUE TITLE
ArgumentError calling poll_interval_average

### ISSUE THREAD

**Issue by nickgal** [ondrejbartas/sidekiq-cron#365]
Running sidekiq@6.5.7 and sidekiq-cron@master

```
2022-09-20T17:06:05.039Z pid=838 tid=1yfy WARN: ArgumentError: wrong number of arguments (given 1, expected 0)
2022-09-20T17:06:05.039Z pid=838 tid=1yfy WARN: /box/ruby/3.1.0/bundler/gems/sidekiq-cron-67db8a1dc7be/lib/sidekiq/cron/poller.rb:46:in `poll_interval_average'
/box/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/scheduled.rb:151:in `random_poll_interval'
/box/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/scheduled.rb:119:in `wait'
/box/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/scheduled.rb:101:in `block in start'
/box/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/component.rb:8:in `watchdog'
/box/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/component.rb:17:in `block in safe_thread'
```

https://github.com/mperham/sidekiq/blob/9fe550dbe9797319de605496e6486eb49c9b1487/lib/sidekiq/scheduled.rb#L151
https://github.com/ondrejbartas/sidekiq-cron/blob/67db8a1dc7be29cc1e944bd91fdb132b4550535d/lib/sidekiq/cron/poller.rb#L46

**Comment by markets** [comment]
Thanks for trying and reporting @nickgal! 

We are about to cut a new release (#364), so good catch! We'll be able to launch a more stable one!

**Comment by engwan** [comment]
Opened https://github.com/ondrejbartas/sidekiq-cron/pull/366 for this.

**Comment by markets** [comment]
@nickgal the fix has been merged to master! Could you please confirm? Thanks!

**Comment by nickgal** [comment]
> @nickgal the fix has been merged to master! Could you please confirm this is working on your side? Thanks!

Confirmed. Thanks
