### ISSUE TITLE
New Feature: english version of cron column

### ISSUE THREAD

**Issue by antulik** [ondrejbartas/sidekiq-cron#47]
add column to web UI to show english version of cron column

for example if cron `0 0 * * *` it would say `midnight every day`

there is ruby gem for that https://github.com/pjungwir/cron2english

**Comment by matthuhiggins** [comment]
I would rather not have this gem introduce a new dependency

**Comment by antulik** [comment]
@matthuhiggins good point, this could be done as an optional extension, which would only be enabled when the gem is already installed.

Just would like to see if other people would find this functionality useful.

**Comment by ondrejbartas** [comment]
I do not want to add more dependencies so it can be done only by asking if class is defined.

Second thing is that it would be nice to se first only text versions and on click event toggle to cron notation.

**Comment by aaronchi** [comment]
I would like to see this as an option

**Comment by dsshap** [comment]
this could be useful
