### ISSUE TITLE
Prune old tasks

### ISSUE THREAD

**Issue by antulik** [ondrejbartas/sidekiq-cron#48]
I've discovered unexpected behaviour, which caused some bugs at the end.

I've used to load tasks from hash on rails load with `Sidekiq::Cron::Job.load_from_hash hash` 

But as it turns out this only adds new tasks to cron, and does not remove old ones. So we ended up with old tasks sitting in the scheduler. 

Would like to suggest add new method to load task and clear old ones if they no longer exist.

**Comment by cernyjakub** [comment]
Did you try ``idekiq::Cron::Job.load_from_hash! hash``?

**Comment by antulik** [comment]
@cernyjakub Thx. `load_from_hash!` is exactly what I was looking for. Didn't see it as it was added in v0.3 but I was on v0.2 version.
