### ISSUE TITLE
Possible sidekiq 3.4.2 issue - views need csrf_tag

### ISSUE THREAD

**Issue by siruguri** [ondrejbartas/sidekiq-cron#52]
I could confirm by changing this in the code - the forms just need a new `<%= csrf_tag %>` input element added to them.

I couldn't do this by myself and send you a pull request because your tests don't pass if I just do a `rake test` - I haven't worked enough with Sinatra apps and standalone gems to figure out if I should have done something else to get the tests to pass. If you can tell me that I'm happy to do this on my own and send you a PR.

**Comment by antulik** [comment]
Same issue here https://github.com/ondrejbartas/sidekiq-cron/pull/50

**Comment by ondrejbartas** [comment]
Fixing in #53  (inspired by #50)
