### ISSUE TITLE
Daily job did not run, how to diagnose?

### ISSUE THREAD

**Issue by skalb** [ondrejbartas/sidekiq-cron#58]
I have a job scheduled to run every day at 00:05 UTC which has always run successfully for the last few months. Today I noticed it didn't run, and I can't figure out why it didn't run and why it returns false for job.should_enqueue?

Here are some relevant logs:
```
irb(main):016:0> job
=> #<Sidekiq::Cron::Job:0x007fdc4c275d78 @name="ActiveUserWorkerJob", @cron="5 0 * * *", @klass="ActiveUserWorker", @status="enabled", @last_enqueue_time=2015-08-05 00:05:00 UTC, @args=[], @message="{\"retry\":true,\"queue\":\"default\",\"class\":\"ActiveUserWorker\",\"args\":[]}">
irb(main):017:0> Time.now.utc
=> 2015-08-06 00:46:06 UTC
irb(main):018:0> job.last_enqueue_time
=> 2015-08-05 00:05:00 UTC
irb(main):019:0> job.should_enque?(Time.now.utc)
=> false
```
Any ideas?

Note: I'm using v0.2.0

**Comment by ondrejbartas** [comment]
Hi this is strange.

pls can you check redis and run this command:
```
ZRANGEBYSCORE 'cron_job: ActiveUserWorkerJob:enqueued' 1438380000 +inf
```

this command should return all enqueued jobs since 2015-08-01.

Past me output pls.

BTW when did you switch to new 0.2.0 version?

**Comment by skalb** [comment]
We've only used the 0.2.0 version actually.

I ended up manually enqueuing the job after reporting the issue, so it's possible that changed things.

```
irb(main):001:0> Sidekiq.redis do |conn|
irb(main):002:1*   p conn.zrangebyscore('cron_job:ActiveUserWorkerJob:enqueued', 1438380000, '+inf')
irb(main):003:1> end
["Tue Aug  4, 12:05 AM UTC", "Wed Aug  5, 12:05 AM UTC", "Thu Aug  6, 12:05 AM UTC"]
=> ["Tue Aug  4, 12:05 AM UTC", "Wed Aug  5, 12:05 AM UTC", "Thu Aug  6, 12:05 AM UTC"]
irb(main):004:0> job = Sidekiq::Cron::Job.all.select { |j| j.name == "ActiveUserWorkerJob" }.first
=> #<Sidekiq::Cron::Job:0x007fc71f03ba68 @name="ActiveUserWorkerJob", @cron="5 0 * * *", @klass="ActiveUserWorker", @status="enabled", @last_enqueue_time=2015-08-06 00:54:00 UTC, @args=[], @message="{\"retry\":true,\"queue\":\"default\",\"class\":\"ActiveUserWorker\",\"args\":[]}">
```

**Comment by ondrejbartas** [comment]
did it happend again? Or was it just one time issue?

**Comment by skalb** [comment]
Just one time issue, so far.

**Comment by jperville** [comment]
If Celluloid constant is not defined, then the Poller class does not register to Celluloid, and no jobs ever get scheduled. Had to make extra care to require 'celluloid' before sidekiq-cron is required by my wrapper class.

**Comment by ondrejbartas** [comment]
@jperville which version of sidekiq have you used? This may be problem becasue sometimes sidekiq is changing dependencies so maybe I will need to fix this globaly.

**Comment by jperville** [comment]
I was using 3.4.2 at the time (and currently 3.5.0).

**Comment by MMartyn** [comment]
This was the what happened to me that lead me to https://github.com/ondrejbartas/sidekiq-cron/pull/109. Basically if something caused a job to resave around the time it was supposed to get enqueued it would get skipped.
