### ISSUE TITLE
Clicking buttons in web ui return 'Forbidden'

### ISSUE THREAD

**Issue by christjin** [ondrejbartas/sidekiq-cron#61]
After upgrade sidekiq to 3.4.2, clicking 'EnqueueNow', 'Disable', 'Enable' and 'Delete' button returns 'Forbidden'.

It may be caused by the new sidekiq requiring authenticity token for the post forms.

**Comment by tfluehmann** [comment]
This issue is solved already here in the github code but not published on rubygems.

**Comment by wbeckeraths2** [comment]
Any expected timeframe when a published version will include this fix?   I just encountered the same issue.

**Comment by ondrejbartas** [comment]
I just released sidekiq-cron v 0.3.1
