### ISSUE TITLE
New Feature: pagination

### ISSUE THREAD

**Issue by JamesChevalier** [ondrejbartas/sidekiq-cron#65]
I would like pagination, similar in behavior to the Scheduled view. I know of another gem, [sidekiq-failures](https://github.com/mhfs/sidekiq-failures), that does this (as an example).

This idea seemed like a good opportunity for me to learn, so I got to work trying to add it myself...

I referred to [the Scheduled view's code](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/web.rb#L171-L173), and I noticed that it relies on the name of the set (in redis) that contains these items. Specifically, this is in the `page("schedule", params[:page], @count)` piece of code. In that line, `"schedule"` is the set in redis that's storing the scheduled jobs.

I followed that down, and found that redis needs this in a number of places. One of them is in order to count the items in that set - [this line](https://github.com/mperham/sidekiq/blob/2fc1d81cc9691c9232a088f1410c5a27fae5e11f/lib/sidekiq/paginator.rb#L19), for example.

I searched in sidekiq-cron, and I found that [the job.rb file](https://github.com/ondrejbartas/sidekiq-cron/blob/08bae57c81aba410c4383410fc3000462bcbe7b4/lib/sidekiq/cron/job.rb#L476) is storing each individual job in its own set named in the format `"cron_job:#{name}:enqueued"`. This makes it impossible to hook into the existing `page("NAMEOFSET", params[:page], @count)` code that sidekiq has for paginating jobs.

I'm wondering a couple things before I move forward any more...
- Why are jobs each put in their own set (`"cron_job:#{name}:enqueued"`)?
- Do you know if it would be safe to put jobs into a single set (e.g. `"sidekiq-cron"`)?

Thanks for all your hard work on this gem! Your README is great, too - thanks for that!

**Comment by ondrejbartas** [comment]
Hi all jobs names are stored in redis key: `cron_jobs ` (set),
Then you have `cron_job:#{name}` (hash) which stores all data needed for job to get executed,
Then there is last `cron_job:#{name}:enqueued `  (sorted set) which stores information about times when job gets into queue (get scheduled).

Sorry for not responding sooner, too much work on other projects :(

If you came up with something, pls create pull request and I will be very happy to help you if you get stucked.
