### ISSUE TITLE
Every 5 seconds sidekiq job

### ISSUE THREAD

**Issue by misteral** [ondrejbartas/sidekiq-cron#67]
How I can do this?

**Comment by ondrejbartas** [comment]
You cant do this by sidekiq-cron currently. How did you manage to do this?

**Comment by ondrejbartas** [comment]
Sidekiq cron is using `rufus-scheduler` and it is supporting cronline to have 5 or six parameters so:
5 parameters: `Minutes Hours Days Months DayOfWeek`
6 parameters: `Seconds Minutes Hours Days Months DayOfWeek`

but when you choose to use seconds, you need to update `Sidekiq.options[:poll_interval]` to lower value than your interval (Sidekiq Cron is started every X second where X is taken from that settings)

Did it help you

**Comment by misteral** [comment]
>  6 parameters: Seconds Minutes Hours Days Months DayOfWeek
Oh, yes. Thanks a lot!
