### ISSUE TITLE
Different time format breaks job scheduling

### ISSUE THREAD

**Issue by rylwin** [ondrejbartas/sidekiq-cron#68]
We recently started using sidekiq-cron (which is awesome!) and came across an odd bug that prevented any jobs from being enqueued. Long story short, our app has a custom default time format that ended up causing `conn.zadd(job_enqueued_key, time.to_f.to_s, formated_last_time(time))` to always return `false`, thereby causing `should_enque?` to always return `false`. 

We fixed this by forking and changing the implementation of `Sidekiq::Cron::Job#formated_last_time` to specify the time string format.

Would there be any interest in merging in a patch that enforces a format for the time? If so, I'd be happy to clean up our code and open a PR. Here's the simple version of our patch: https://github.com/ValencePM/sidekiq-cron/commit/a75a72721cf783c1ef9fbd2a66815edd579bed27.

**Comment by ondrejbartas** [comment]
Hi,

I didn't expect that to happen but yes sure thing create pull request pls. BTW why don't you use for example: `last_time(now).getutc.iso8601` which is standard?

**Comment by rylwin** [comment]
Great! I'll work on a pull request. And I'll switch to using `iso8601` as you suggest -- great idea :+1:
