### ISSUE TITLE
Load jobs from the application database

### ISSUE THREAD

**Issue by zedalaye** [ondrejbartas/sidekiq-cron#69]
I want to migrate from clockwork to sidekiq-cron but a very interesting feature with clockwork is its ability to load "dynamic" jobs from the database (https://github.com/tomykaira/clockwork#use-with-database-events).

Is it possible to replicate this behaviour with sidekiq-cron ?

**Comment by ondrejbartas** [comment]
Hi,
you can do this by creating one small job, which will take all jobs from database and use:
```ruby
Sidekiq::Cron::Job.load_from_hash! hash
# or
Sidekiq::Cron::Job.load_from_array! array
```
which will take your jobs and overwrite jobs to match their database state.

**Comment by ondrejbartas** [comment]
@zedalaye pls let me know if it was working for your needs

**Comment by zedalaye** [comment]
I have not tested. I don't know what "hash" and "array" must contain in fact.

**Comment by ondrejbartas** [comment]
Read readme pls:

Load more jobs from hash:

```ruby
hash = {
  'name_of_job' => {
    'class' => 'MyClass',
    'cron'  => '1 * * * *',
    'args'  => '(OPTIONAL) [Array or Hash]'
  },
  'My super iber cool job' => {
    'class' => 'SecondClass',
    'cron'  => '*/5 * * * *'
  }
}

Sidekiq::Cron::Job.load_from_hash hash
```
Load more jobs from array:

```ruby
array = [
  {
    'name'  => 'name_of_job',
    'class' => 'MyClass',
    'cron'  => '1 * * * *',
    'args'  => '(OPTIONAL) [Array or Hash]'
  },
  {
    'name'  => 'Cool Job for Second Class',
    'class' => 'SecondClass',
    'cron'  => '*/5 * * * *'
  }
]

Sidekiq::Cron::Job.load_from_array array
```
