### ISSUE TITLE
LoadError: no such file to load -- sidekiq/actor in sidekiq v4.0.0.pre1

### ISSUE THREAD

**Issue by muhammet** [ondrejbartas/sidekiq-cron#72]
I got this error when upgrade to sidekiq v4.0.0.pre1

**Comment by disbelief** [comment]
Same error with Sidekiq 4.0.0.pre2. Also appears that the `Job` and `Poller` classes depend on `sidekiq/actor` which no longer exists in Sidekiq 4.

**Comment by ondrejbartas** [comment]
@disbelief  @muhammet I have release sidekiq-cron version 0.4.0 where it should be fixed

**Comment by Soliah** [comment]
Worked for me with Sidekiq 4.0.1.

**Comment by dfabreguette-ap** [comment]
Having the same one ! Here's my stacktrace if that can help !
http://pastebin.com/N0SU6vMM

**Comment by ondrejbartas** [comment]
@dfabreguette-ap pls use sidekiq-cron version 0.4.0
