### ISSUE TITLE
Allow intervals for scheduler

### ISSUE THREAD

**Issue by fabn** [ondrejbartas/sidekiq-cron#74]
I'm trying to convert an existing resque + resque-scheduler application to sidekiq + sidekiq-cron.

I already saw #16 however I think that allowing intervals for jobs does have an added value to this gem.

In my use case I have an admin interface where administrators can specify intervals to run jobs and allowing them to specify as intervals is much more user friendly that having them enter job intervals as cron jobs.

One can express some interval as [multiple cron entries](https://github.com/ondrejbartas/sidekiq-cron/issues/16#issuecomment-36374575) however this lead to multiple `Sidekiq::Cron::Job` for the same job and this is very ugly. I have a database record with job specification and a callback that convert record attributes to job instance. If one create a job that has to be mapped to multiple `Sidekiq::Cron::Job`s code will become a mess.

Finally there are some intervals that cannot be converted to cron (or where its conversion is a big mess and not accurate), see for instance [this example](http://stackoverflow.com/q/745901/518204) or think about "repeat every 37 minutes".

A very naive implementation would be to rely a rufus scheduler and use it for recurring jobs, something like:

``` ruby
# Somewhere in initialization code
Sidekiq::Cron::Job.all.select { |j| j.interval? }.each do |job|
  job_id = scheduler.every job.interval do
    job.enque! # Don't know if this is enough to enqueue the job 
    # In rails would be something like
    # job.klass.constantize.perform_async(job.arguments)
  end
  # Persist job id, used later to cancel the job if needed
  job.every_id = job.id
  job.save
end
```

What do you think?

**Comment by fabn** [comment]
Also since sidekiq has changed, as noticed in #72, Poller class need a refactor. 

It may be a good idea to rewrite it to only depend on rufus scheduler and use a single monkey patch to sidekiq code to launch a rufus scheduler which will take care of everything.

**Comment by ondrejbartas** [comment]
will look into this
