### ISSUE TITLE
Inconsistency (klass/class) in Readme

### ISSUE THREAD

**Issue by denispeplin** [ondrejbartas/sidekiq-cron#75]
Here `klass` is used: https://github.com/ondrejbartas/sidekiq-cron#getting-started
And here `class` (in the end of the section): https://github.com/ondrejbartas/sidekiq-cron#adding-cron-job

We are using `class`, and all works fine. What we really should use, or it doesn't matter?

**Comment by ondrejbartas** [comment]
thank you, I hope I have fixed it
