### ISSUE TITLE
Re-namespace?

### ISSUE THREAD

**Issue by mperham** [ondrejbartas/sidekiq-cron#78]
I noticed this gem uses the Sidekiq module by putting its code in Sidekiq::Cron.  This is a problem as it or other constants you add can collide with Sidekiq's code.  Your gem's namespace should be SidekiqCron.  Would you change the namespace to avoid any accidental collisions?

**Comment by ondrejbartas** [comment]
@mperham I was always looking at your code in Sidekiq and making sure that my Gem will not break anything.  Btw it would be great if you could have option to setup custom pollers so other gems could be started with sidekiq and not to monkey patch launcher https://github.com/ondrejbartas/sidekiq-cron/blob/master/lib/sidekiq/cron/launcher.rb

**Comment by mperham** [comment]
@ondrejbartas Please see Process Lifecycle events here https://github.com/mperham/sidekiq/blob/master/Changes.md#300 They aren't well documented but that's how Pro and Enterprise start their additional features.

**Comment by ondrejbartas** [comment]
Thank you will update gem tommorow and hopefully release new version with namespaced and updated life cycle startup.

**Comment by joevandyk** [comment]
Should this be closed?
