### ISSUE TITLE
Job did not get updated on heroku

### ISSUE THREAD

**Issue by manish-thinkbridge** [ondrejbartas/sidekiq-cron#80]
I have written a job which runs every 1 min, deployed to heroku, it ran perfectly fine.
Then I updated that job to run in every 120 mins, when I deployed to heroku the job is still running every 1 min. (In my local env. I changed 1min->5min, it worked fine)
I am using RedisToGo addon on heroku.
The job creation script is in one of the initializers which is as follows:

```
#initializers/sidekiq.rb

hash = {
  'etl_job' => {
    'class' => 'EtlWorker',
    'cron'  => '*/120 * * * *'
  }
}

if Sidekiq.server?
  Sidekiq::Cron::Job.load_from_hash! hash
end
```

I tried restarting the worker, app and even RedisToGo server, still no change.
Am I doing something wrong?

**Comment by ondrejbartas** [comment]
Hi job settings is saved in redis so did you updated redis configuration? You can do it by `Sidekiq::Cron::Job.load_from_hash!` You do not need to restart sidekiq for changing cron.

**Comment by ondrejbartas** [comment]
BTW why do you do:
```
if Sidekiq.server?
```

**Comment by ondrejbartas** [comment]
try to remove that.

**Comment by manish-thinkbridge** [comment]
Thanks for reply.
I was just following the readme that's why used Sidekiq.server?
Anyways I got the problem.
It was invalid cron expression.
For 120 mins i.e. 2 hours, correct cron expression is like this '0 */2 * * *'

**Comment by ondrejbartas** [comment]
@manish-thinkbridge so everything work fine for you?

**Comment by manish-thinkbridge** [comment]
oh .... yeah :+1:
