### ISSUE TITLE
bin/rails:6: warning: already initialized constant APP_PATH

### ISSUE THREAD

**Issue by Frylock13** [ondrejbartas/sidekiq-cron#82]
Hi, 

I've got this error when I add sidekiq-cron in my Gemfile and try to start a server:

```
bin/rails:6: warning: already initialized constant APP_PATH
/home/user/projects/commit/bin/rails:6: warning: previous definition of APP_PATH was here
Usage: rails COMMAND [ARGS]
```
Sidekiq 4.0.1
Ruby 2.2.2
Rails 4.2.5

Any ideas why this happens?

**Comment by ondrejbartas** [comment]
This is not related to sidekiq and sidekiq-cron. This is related to RVM or rbenv you are using.
pls follow: http://stackoverflow.com/questions/23402820/rails-server-bin-rails6-warning-already-initialized-constant-app-path-error
