### ISSUE TITLE
Clicking Enqueue Now on Sidekiq web dashboard schedules the same job

### ISSUE THREAD

**Issue by krzkrzkrz** [ondrejbartas/sidekiq-cron#93]
On the Sidekiq web dashboard. Clicking the "Enqueue Now" button schedules the same job. Which means, multiple jobs of the same kind are run concurrently.

Readme says "Checks for new jobs to schedule every 10 seconds and doesn't schedule the same job multiple times when more than one Sidekiq worker is running."

Wondering if this this the expected behaviour?

**Comment by ondrejbartas** [comment]
@krzkrzkrz difference is between scheduling and running jobs.

Scheduling will enforce to schedule job only once (without worry about process count), they are basically added into queue.

Running jobs is take job from queue and run it by worker (this is Sidekiq responsibility)

**Comment by krzkrzkrz** [comment]
Thanks for the explanation
