### ISSUE TITLE
Not able to run a job at a specific hour every day

### ISSUE THREAD

**Issue by phyzalis** [ondrejbartas/sidekiq-cron#94]
Hello

I am not able to run a job at a specific hour every day.
My time zone is utc + 1 
In my config/application.rb :  

    config.time_zone = 'Paris'
    config.active_record.default_timezone = :local

Here is a sample of my cron for a task running every day, every minutes at 1pm utc+1:
    * 12 * * * *

I tried like this too
    * 12 * * * * Etc/UTC
and like this
    * 13 * * * * Europe/Paris

To be sure I have tried * 13 * * * * and 0 13 * * * * too but without any success

I have nothing in last enque

If I try with something like * * * * * * or 5 * * * * *, it works fine
If I click on "Enqueue now" it works fine

Do you have any advice about how I can find what is wrong or any lead on how to make this work?

**Comment by phyzalis** [comment]
I've forgot something important, I am using it like this:

    Sidekiq::Cron::Job.new(name: my_uniq_job_name, cron: * 12 * * * *, class: 'MyJob', args: {id: self.id})

**Comment by samjacoby** [comment]
I wonder if this is related to #89?

**Comment by phyzalis** [comment]
Yes maybe

**Comment by phyzalis** [comment]
Ok so my issue was my cron format for RufusScheduler as it must be a 5 cron

    man 5 crontab
