### ISSUE TITLE
Expiring a cron job?

### ISSUE THREAD

**Issue by samjacoby** [ondrejbartas/sidekiq-cron#95]
I'm looking at a use-case where we want to run a job every ten minutes, say, for a month. Any thoughts on the best way to go about that? 

I see that [sidekiq pro](https://github.com/mperham/sidekiq/wiki/Expiring-Jobs) has support for expiring jobs, but that's not an option at the moment. 

Would be happy to implement against `sidekiq-cron` and PR, but curious if anyone has thoughts.

**Comment by ondrejbartas** [comment]
I never thought about this, but sure, this can be nice use case 💃
