### ISSUE TITLE
Does my sidekiq.rb config look sane?

### ISSUE THREAD

**Issue by krzkrzkrz** [ondrejbartas/sidekiq-cron#98]
Just checking. At `config/initializers/sidekiq.rb`, I have got:

```
require 'sidekiq/web'
require 'sidekiq/cron/web'
require 'sidekiq-cron'

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['REDIS_SERVER_URL'], namespace: "sidekiq_#{Rails.env}" }
end

Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDIS_SERVER_URL'], namespace: "sidekiq_#{Rails.env}" }
end

Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  [user, password] == [ENV['AUTHORIZED_USERNAME'], ENV['AUTHORIZED_PASSWORD']]
end

# Sidekiq cron
hash = {
  'Send Slack Summary' => {
    'class' => 'SendSlackSummaryWorker',
    'cron'  => '*/30 * * * *', # Run every 30 minutes
    # 'args'  => [5]
  }
}

Sidekiq::Cron::Job.load_from_hash hash
```

The Readme wasn't very clear on where to place `Sidekiq::Cron::Job.load_from_hash hash` in a Rails environment.

Does above configuration look fine?

Deploying on AWS OpsWorks. When running `bundle exec rake db:migrate --trace`. I get the following error:

```
Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
```

For some reason, it is trying to connect to the local Redis server.

Problem does not happen locally. Just on Staging and Production.
Readme suggests checking for `Sidekiq.server?`. Dont know if this helps.

Any ideas?

**Comment by hderms** [comment]
@krzkrzkrz are you using elasticache?

**Comment by krzkrzkrz** [comment]
@hderms No, using Redistogo

**Comment by BrahimDahmani** [comment]
+1
